; COLLISION CHECKS
CHECK_COLLISION:
    BANKSEL TEMP3
    MOVF TEMP3, W
    BANKSEL PLAYER_LANE
    SUBWF PLAYER_LANE, W
    BTFSS STATUS, 2
    RETURN
    BANKSEL ISR_FLAGS
    BSF ISR_FLAGS, FLAG_COLLISION
    RETURN

