; EEPROM READ
EEPROM_READ:
    BANKSEL EEADR
    MOVWF EEADR
    BANKSEL EECON1
    BCF EECON1, 7
    BSF EECON1, 0
    BANKSEL EEDATA
    MOVF EEDATA, W
    BANKSEL GAME_STATE
    RETURN

; EEPROM_WRITE_BYTE
EEPROM_WRITE_BYTE:
    BANKSEL TEMP2
    MOVF TEMP2, W
    BANKSEL EEADR
    MOVWF EEADR
    BANKSEL TEMP1
    MOVF TEMP1, W
    BANKSEL EEDATA
    MOVWF EEDATA
    BANKSEL EECON1
    BCF EECON1, 7
    BSF EECON1, 2
    BCF INTCON, 7
    MOVLW 0x55
    MOVWF EECON2
    MOVLW 0xAA
    MOVWF EECON2
    BSF EECON1, 1
    BSF INTCON, 7
EWB_WAIT:
    BTFSC EECON1, 1
    GOTO EWB_WAIT
    BCF EECON1, 2
    BANKSEL GAME_STATE
    RETURN

; EEPROM_LOAD_HISCORE
EEPROM_LOAD_HISCORE:
    MOVLW EE_SENTINEL
    CALL EEPROM_READ
    MOVWF TEMP1
    MOVLW EE_VALID
    SUBWF TEMP1, W
    BTFSS STATUS, 2
    GOTO ELH_INVALID

    MOVLW EE_HISCORE_LO
    CALL EEPROM_READ
    BANKSEL HISCORE_LO
    MOVWF HISCORE_LO

    MOVLW EE_HISCORE_HI
    CALL EEPROM_READ
    BANKSEL HISCORE_HI
    MOVWF HISCORE_HI
    RETURN

ELH_INVALID:
    BANKSEL HISCORE_LO
    CLRF HISCORE_LO
    CLRF HISCORE_HI
    RETURN

; EEPROM_SAVE_HISCORE
EEPROM_SAVE_HISCORE:
    BANKSEL HISCORE_LO
    MOVFFREG HISCORE_LO, TEMP1
    MOVLF EE_HISCORE_LO, TEMP2
    CALL EEPROM_WRITE_BYTE

    BANKSEL HISCORE_HI
    MOVFFREG HISCORE_HI, TEMP1
    MOVLF EE_HISCORE_HI, TEMP2
    CALL EEPROM_WRITE_BYTE

    MOVLF EE_VALID, TEMP1
    MOVLF EE_SENTINEL, TEMP2
    CALL EEPROM_WRITE_BYTE
    RETURN

; CHECK_AND_SAVE_HISCORE
CHECK_AND_SAVE_HISCORE:
    BANKSEL NEW_BEST
    CLRF NEW_BEST

    BANKSEL SCORE_HI
    MOVF SCORE_HI, W
    BANKSEL HISCORE_HI
    SUBWF HISCORE_HI, W
    BTFSS STATUS, 0
    GOTO CASH_NEW_BEST
    BTFSS STATUS, 2
    RETURN

    BANKSEL SCORE_LO
    MOVF SCORE_LO, W
    BANKSEL HISCORE_LO
    SUBWF HISCORE_LO, W
    BTFSS STATUS, 0
    GOTO CASH_NEW_BEST
    RETURN

CASH_NEW_BEST:
    BANKSEL SCORE_LO
    MOVFFREG SCORE_LO, HISCORE_LO
    MOVFFREG SCORE_HI, HISCORE_HI
    MOVLF 1, NEW_BEST
    RETURN

