; GAME_RESET
GAME_RESET:
    BANKSEL GAME_STATE
    MOVLF STATE_PLAY, GAME_STATE
    MOVLF FUEL_MAX, FUEL_LEVEL
    MOVLF FUEL_MAX, PREV_FUEL
    MOVLF FUEL_DEC_INT,FUEL_TICK
    MOVLF SPEED_LVL1, SPEED_LEVEL
    MOVLF 1, LEVEL
    MOVLF 1, PLAYER_LANE
    MOVLF 1, PREV_LANE
    CLR16 SCORE_LO, SCORE_HI
    CLRF ROAD_SCROLL
    CLRF GAME_TICK
    CLRF ACTIVE_ENEMIES
    MOVLF SPAWN_LVL1, SPAWN_TIMER
    MOVLF ENEMY_INACTIVE, EN0_LANE
    MOVLF ENEMY_INACTIVE, EN1_LANE
    MOVLF ENEMY_INACTIVE, EN2_LANE
    MOVLF ENEMY_INACTIVE, FUEL_LANE
    CLRF EN0_ROW
    CLRF EN1_ROW
    CLRF EN2_ROW
    MOVLF 0x01, HUD_DIRTY
    CLRF NEW_BEST
    CLRF BLINK_FLAG
    MOVLF 0xAC, LFSR_HI
    MOVLF 0xE1, LFSR_LO

    CALL GLCD_CLEAR_ALL
    CALL DRAW_HUD
    CALL DRAW_ROAD
    CALL DRAW_CAR

    BANKSEL PORTC
    BSF PORTC, 2
    RETURN

; SCORE_TO_BCD_3
SCORE_TO_BCD_3:
    CLRF TEMP1
    CLRF TEMP2
    BANKSEL SCORE_LO
    MOVF SCORE_LO, W
    BANKSEL TEMP3
    MOVWF TEMP3
S3H:
    MOVLW 100
    SUBWF TEMP3, W
    BTFSS STATUS, 0
    GOTO S3T
    MOVWF TEMP3
    INCF TEMP1, F
    GOTO S3H
S3T:
    MOVLW 10
    SUBWF TEMP3, W
    BTFSS STATUS, 0
    GOTO S3DONE
    MOVWF TEMP3
    INCF TEMP2, F
    GOTO S3T
S3DONE:
    RETURN

HISCORE_TO_BCD_3:
    CLRF TEMP1
    CLRF TEMP2
    BANKSEL HISCORE_LO
    MOVF HISCORE_LO, W
    BANKSEL TEMP3
    MOVWF TEMP3
    GOTO S3H

DRAW_3DIGITS:
    BANKSEL SCORE_DISP
    MOVF TEMP2, W
    MOVWF SCORE_DISP
    MOVF TEMP3, W
    MOVWF PREV_FUEL
    MOVF TEMP1, W
    ADDLW FC_0
    MOVWF TEMP1
    CALL DRAW_CHAR
    BANKSEL SCORE_DISP
    MOVF SCORE_DISP, W
    ADDLW FC_0
    MOVWF TEMP1
    CALL DRAW_CHAR
    BANKSEL PREV_FUEL
    MOVF PREV_FUEL, W
    ADDLW FC_0
    MOVWF TEMP1
    CALL DRAW_CHAR
    RETURN

; DRAW_PRESS_SELECT
DRAW_PRESS_SELECT:
    MOVLF 7, DRAW_PAGE
    MOVLF 28, DRAW_X
    MOVLF FC_P, TEMP1
    CALL DRAW_CHAR
    MOVLF FC_R, TEMP1
    CALL DRAW_CHAR
    MOVLF FC_E, TEMP1
    CALL DRAW_CHAR
    MOVLF FC_S, TEMP1
    CALL DRAW_CHAR
    MOVLF FC_S, TEMP1
    CALL DRAW_CHAR
    MOVLF FC_SPC, TEMP1
    CALL DRAW_CHAR
    MOVLF FC_S, TEMP1
    CALL DRAW_CHAR
    MOVLF FC_E, TEMP1
    CALL DRAW_CHAR
    MOVLF FC_L, TEMP1
    CALL DRAW_CHAR
    MOVLF FC_E, TEMP1
    CALL DRAW_CHAR
    MOVLF FC_C, TEMP1
    CALL DRAW_CHAR
    MOVLF FC_T, TEMP1
    CALL DRAW_CHAR
    RETURN

; DRAW_MENU_CURSOR
DRAW_MENU_CURSOR:
    MOVLF 6, DRAW_PAGE
    MOVLF 46, DRAW_X
    MOVLF FC_GT, TEMP1
    CALL DRAW_CHAR
    RETURN

; DRAW_HI_HEADER
DRAW_HI_HEADER:
    CLRF DRAW_PAGE
    CLRF DRAW_X
    MOVLF FC_H, TEMP1
    CALL DRAW_CHAR
    MOVLF FC_I, TEMP1
    CALL DRAW_CHAR
    MOVLF FC_COL, TEMP1
    CALL DRAW_CHAR
    CALL HISCORE_TO_BCD_3
    CALL DRAW_3DIGITS

    MOVLF 1, DRAW_PAGE
    CLRF DRAW_X
DHH_DIV_LOOP:
    MOVLF 0x08, DISP_BYTE
    CALL GLCD_PUT_BYTE
    INCF DRAW_X, F
    MOVLW 128
    SUBWF DRAW_X, W
    BTFSS STATUS, 2
    GOTO DHH_DIV_LOOP
    RETURN

; DRAW_NEW_RECORD
DRAW_NEW_RECORD:
    MOVLF 4, DRAW_PAGE
    MOVLF 31, DRAW_X
    MOVLF FC_N, TEMP1
    CALL DRAW_CHAR
    MOVLF FC_E, TEMP1
    CALL DRAW_CHAR
    MOVLF FC_W, TEMP1
    CALL DRAW_CHAR
    MOVLF FC_SPC, TEMP1
    CALL DRAW_CHAR
    MOVLF FC_R, TEMP1
    CALL DRAW_CHAR
    MOVLF FC_E, TEMP1
    CALL DRAW_CHAR
    MOVLF FC_C, TEMP1
    CALL DRAW_CHAR
    MOVLF FC_O, TEMP1
    CALL DRAW_CHAR
    MOVLF FC_R, TEMP1
    CALL DRAW_CHAR
    MOVLF FC_D, TEMP1
    CALL DRAW_CHAR
    MOVLF FC_EX, TEMP1
    CALL DRAW_CHAR
    RETURN

; DRAW_BOOT_SPLASH
DRAW_BOOT_SPLASH:
    MOVLF 2, DRAW_PAGE
    MOVLF 34, DRAW_X
    MOVLF FC_R, TEMP1
    CALL DRAW_CHAR
    MOVLF FC_A, TEMP1
    CALL DRAW_CHAR
    MOVLF FC_C, TEMP1
    CALL DRAW_CHAR
    MOVLF FC_I, TEMP1
    CALL DRAW_CHAR
    MOVLF FC_N, TEMP1
    CALL DRAW_CHAR
    MOVLF FC_G, TEMP1
    CALL DRAW_CHAR
    MOVLF FC_SPC, TEMP1
    CALL DRAW_CHAR
    MOVLF FC_C, TEMP1
    CALL DRAW_CHAR
    MOVLF FC_A, TEMP1
    CALL DRAW_CHAR
    MOVLF FC_R, TEMP1
    CALL DRAW_CHAR

    MOVLF 4, DRAW_PAGE
    MOVLF 40, DRAW_X
    MOVLF FC_B, TEMP1
    CALL DRAW_CHAR
    MOVLF FC_Y, TEMP1
    CALL DRAW_CHAR
    MOVLF FC_SPC, TEMP1
    CALL DRAW_CHAR
    MOVLF FC_A, TEMP1
    CALL DRAW_CHAR
    MOVLF FC_Y, TEMP1
    CALL DRAW_CHAR
    MOVLF FC_U, TEMP1
    CALL DRAW_CHAR
    MOVLF FC_S, TEMP1
    CALL DRAW_CHAR
    MOVLF FC_H, TEMP1
    CALL DRAW_CHAR

    MOVLF 5, DRAW_PAGE
    MOVLF 49, DRAW_X
    MOVLF FC_Y, TEMP1
    CALL DRAW_CHAR
    MOVLF FC_A, TEMP1
    CALL DRAW_CHAR
    MOVLF FC_J, TEMP1
    CALL DRAW_CHAR
    MOVLF FC_A, TEMP1
    CALL DRAW_CHAR
    MOVLF FC_T, TEMP1
    CALL DRAW_CHAR

    MOVLW 78
    CALL DELAY_TICKS
    RETURN

; DRAW_MENU
DRAW_MENU:
    CALL GLCD_CLEAR_ALL

    CALL DRAW_HI_HEADER

    MOVLF 2, DRAW_PAGE
    MOVLF 34, DRAW_X
    MOVLF FC_R, TEMP1
    CALL DRAW_CHAR
    MOVLF FC_A, TEMP1
    CALL DRAW_CHAR
    MOVLF FC_C, TEMP1
    CALL DRAW_CHAR
    MOVLF FC_I, TEMP1
    CALL DRAW_CHAR
    MOVLF FC_N, TEMP1
    CALL DRAW_CHAR
    MOVLF FC_G, TEMP1
    CALL DRAW_CHAR
    MOVLF FC_SPC, TEMP1
    CALL DRAW_CHAR
    MOVLF FC_C, TEMP1
    CALL DRAW_CHAR
    MOVLF FC_A, TEMP1
    CALL DRAW_CHAR
    MOVLF FC_R, TEMP1
    CALL DRAW_CHAR

    MOVLF 3, DRAW_PAGE
    MOVLF 58, DRAW_X
    MOVLW CAR_TOP_0
    MOVWF FSR
    CALL DRAW_SPRITE_ROW
    MOVLF 4, DRAW_PAGE
    MOVLF 58, DRAW_X
    MOVLW CAR_BOT_0
    MOVWF FSR
    CALL DRAW_SPRITE_ROW

    CALL DRAW_MENU_CURSOR
    MOVLF 6, DRAW_PAGE
    MOVLF 58, DRAW_X
    MOVLF FC_P, TEMP1
    CALL DRAW_CHAR
    MOVLF FC_L, TEMP1
    CALL DRAW_CHAR
    MOVLF FC_A, TEMP1
    CALL DRAW_CHAR
    MOVLF FC_Y, TEMP1
    CALL DRAW_CHAR

    CALL DRAW_PRESS_SELECT
    RETURN

; DRAW_GAMEOVER_SCREEN
DRAW_GAMEOVER_SCREEN:
    CALL GLCD_CLEAR_ALL
    CALL DRAW_HI_HEADER

    MOVLF 2, DRAW_PAGE
    MOVLF 37, DRAW_X
    MOVLF FC_G, TEMP1
    CALL DRAW_CHAR
    MOVLF FC_A, TEMP1
    CALL DRAW_CHAR
    MOVLF FC_M, TEMP1
    CALL DRAW_CHAR
    MOVLF FC_E, TEMP1
    CALL DRAW_CHAR
    MOVLF FC_SPC, TEMP1
    CALL DRAW_CHAR
    MOVLF FC_O, TEMP1
    CALL DRAW_CHAR
    MOVLF FC_V, TEMP1
    CALL DRAW_CHAR
    MOVLF FC_E, TEMP1
    CALL DRAW_CHAR
    MOVLF FC_R, TEMP1
    CALL DRAW_CHAR

    MOVLF 3, DRAW_PAGE
    MOVLF 43, DRAW_X
    MOVLF FC_S, TEMP1
    CALL DRAW_CHAR
    MOVLF FC_C, TEMP1
    CALL DRAW_CHAR
    MOVLF FC_COL, TEMP1
    CALL DRAW_CHAR
    CALL SCORE_TO_BCD_3
    CALL DRAW_3DIGITS

    BANKSEL NEW_BEST
    MOVF NEW_BEST, F
    BTFSC STATUS, 2
    GOTO DGO_SKIP_NR
    CALL DRAW_NEW_RECORD
DGO_SKIP_NR:

    MOVLF 5, DRAW_PAGE
    MOVLF 37, DRAW_X
    MOVLF FC_B, TEMP1
    CALL DRAW_CHAR
    MOVLF FC_E, TEMP1
    CALL DRAW_CHAR
    MOVLF FC_S, TEMP1
    CALL DRAW_CHAR
    MOVLF FC_T, TEMP1
    CALL DRAW_CHAR
    MOVLF FC_COL, TEMP1
    CALL DRAW_CHAR
    CALL HISCORE_TO_BCD_3
    CALL DRAW_3DIGITS

    CALL DRAW_PRESS_SELECT
    RETURN

DRAW_HUD:
    BANKSEL DRAW_PAGE
    MOVLF HUD_PAGE, DRAW_PAGE

    BANKSEL FUEL_LEVEL
    MOVF FUEL_LEVEL, W
    MOVWF TEMP1
    CLRF TEMP2
DIV3_LOOP:
    MOVLW 3
    SUBWF TEMP1, W
    BTFSS STATUS, 0
    GOTO DIV3_DONE
    MOVWF TEMP1
    BANKSEL TEMP2
    INCF TEMP2, F
    GOTO DIV3_LOOP
DIV3_DONE:
    BANKSEL DRAW_X
    CLRF DRAW_X
    BANKSEL TEMP2
    MOVF TEMP2, W
    MOVWF LOOP_CNT
HDF_FILL:
    BANKSEL LOOP_CNT
    MOVF LOOP_CNT, F
    BTFSC STATUS, 2
    GOTO HDF_EMPTY
    BANKSEL DISP_BYTE
    MOVLF 0x7E, DISP_BYTE
    CALL GLCD_PUT_BYTE
    BANKSEL DRAW_X
    INCF DRAW_X, F
    BANKSEL LOOP_CNT
    DECF LOOP_CNT, F
    GOTO HDF_FILL
HDF_EMPTY:
    BANKSEL DRAW_X
    MOVLW 40
    SUBWF DRAW_X, W
    BTFSC STATUS, 0
    GOTO HDF_SEP
    BANKSEL DISP_BYTE
    MOVLF 0x42, DISP_BYTE
    CALL GLCD_PUT_BYTE
    BANKSEL DRAW_X
    INCF DRAW_X, F
    GOTO HDF_EMPTY
HDF_SEP:
    BANKSEL DRAW_X
    MOVLF 40, DRAW_X
    BANKSEL DISP_BYTE
    MOVLF 0xFF, DISP_BYTE
    CALL GLCD_PUT_BYTE

    BANKSEL DRAW_X
    MOVLF 50, DRAW_X
    BANKSEL LEVEL
    MOVF LEVEL, W
    MOVWF LOOP_CNT
HDL_LOOP:
    BANKSEL LOOP_CNT
    MOVF LOOP_CNT, F
    BTFSC STATUS, 2
    GOTO HDS_SCORE
    BANKSEL DISP_BYTE
    MOVLF 0x7E, DISP_BYTE
    CALL GLCD_PUT_BYTE
    BANKSEL DRAW_X
    INCF DRAW_X, F
    BANKSEL LOOP_CNT
    DECF LOOP_CNT, F
    GOTO HDL_LOOP

HDS_SCORE:
    MOVLF 86, DRAW_X
    MOVLF FC_S, TEMP1
    CALL DRAW_CHAR
    MOVLF FC_C, TEMP1
    CALL DRAW_CHAR
    MOVLF FC_COL, TEMP1
    CALL DRAW_CHAR
    CALL SCORE_TO_BCD_3
    CALL DRAW_3DIGITS

    BANKSEL HUD_DIRTY
    CLRF HUD_DIRTY
    RETURN

; DRAW_ROAD
DRAW_ROAD:
    BANKSEL DRAW_PAGE
    MOVLF ROAD_START_PAGE, DRAW_PAGE
DR_PAGE_LOOP:
    BANKSEL DRAW_PAGE
    MOVF DRAW_PAGE, W
    BANKSEL ROAD_SCROLL
    ADDWF ROAD_SCROLL, W
    ANDLW 0x01
    BTFSC STATUS, 2
    GOTO DR_GAP
    BANKSEL DISP_BYTE
    MOVLF 0xFF, DISP_BYTE
    GOTO DR_DIVS
DR_GAP:
    BANKSEL DISP_BYTE
    MOVLF 0x00, DISP_BYTE
DR_DIVS:
    BANKSEL DRAW_X
    MOVLF DIV1_COL, DRAW_X
    CALL GLCD_PUT_BYTE
    BANKSEL DRAW_X
    MOVLF DIV2_COL, DRAW_X
    CALL GLCD_PUT_BYTE
    BANKSEL DRAW_PAGE
    MOVLW 7
    SUBWF DRAW_PAGE, W
    BTFSS STATUS, 2
    GOTO DR_NEXT
    BANKSEL DRAW_X
    CLRF DRAW_X
DR_BORDER:
    BANKSEL DISP_BYTE
    MOVLF 0xFF, DISP_BYTE
    CALL GLCD_PUT_BYTE
    BANKSEL DRAW_X
    INCF DRAW_X, F
    MOVLW 128
    SUBWF DRAW_X, W
    BTFSS STATUS, 2
    GOTO DR_BORDER
DR_NEXT:
    BANKSEL DRAW_PAGE
    INCF DRAW_PAGE, F
    MOVLW 8
    SUBWF DRAW_PAGE, W
    BTFSS STATUS, 2
    GOTO DR_PAGE_LOOP
    RETURN

; LANE X HELPERS
GET_LANE_X:
    BANKSEL PLAYER_LANE
    MOVF PLAYER_LANE, W
    ANDLW 0xFF
    BTFSC STATUS, 2
    GOTO GLX_0
    MOVLW 1
    BANKSEL PLAYER_LANE
    SUBWF PLAYER_LANE, W
    BTFSC STATUS, 2
    GOTO GLX_1
    MOVLF LANE2_X + CAR_OFF, CAR_X
    RETURN
GLX_0:
    MOVLF LANE0_X + CAR_OFF, CAR_X
    RETURN
GLX_1:
    MOVLF LANE1_X + CAR_OFF, CAR_X
    RETURN

GET_PREV_LANE_X:
    BANKSEL PREV_LANE
    MOVF PREV_LANE, W
    ANDLW 0xFF
    BTFSC STATUS, 2
    GOTO GPX_0
    MOVLW 1
    BANKSEL PREV_LANE
    SUBWF PREV_LANE, W
    BTFSC STATUS, 2
    GOTO GPX_1
    MOVLF LANE2_X + CAR_OFF, CAR_X
    RETURN
GPX_0:
    MOVLF LANE0_X + CAR_OFF, CAR_X
    RETURN
GPX_1:
    MOVLF LANE1_X + CAR_OFF, CAR_X
    RETURN

GET_ENEMY_X:
    BANKSEL TEMP3
    MOVF TEMP3, W
    ANDLW 0xFF
    BTFSC STATUS, 2
    GOTO GEX_0
    MOVLW 1
    SUBWF TEMP3, W
    BTFSC STATUS, 2
    GOTO GEX_1
    MOVLF LANE2_X + CAR_OFF, CAR_X
    RETURN
GEX_0:
    MOVLF LANE0_X + CAR_OFF, CAR_X
    RETURN
GEX_1:
    MOVLF LANE1_X + CAR_OFF, CAR_X
    RETURN

; SPRITE ROWS
DRAW_SPRITE_ROW:
    BANKSEL SPRITE_IDX
    MOVLF CAR_WIDTH, SPRITE_IDX
DSR_LOOP:
    MOVF INDF, W
    BANKSEL DISP_BYTE
    MOVWF DISP_BYTE
    CALL GLCD_PUT_BYTE
    INCF FSR, F
    BANKSEL DRAW_X
    INCF DRAW_X, F
    BANKSEL SPRITE_IDX
    DECF SPRITE_IDX, F
    BTFSS STATUS, 2
    GOTO DSR_LOOP
    RETURN

ERASE_SPRITE_ROW:
    BANKSEL SPRITE_IDX
    MOVLF CAR_WIDTH, SPRITE_IDX
ESR_LOOP:
    BANKSEL DISP_BYTE
    MOVLF 0x00, DISP_BYTE
    CALL GLCD_PUT_BYTE
    BANKSEL DRAW_X
    INCF DRAW_X, F
    BANKSEL SPRITE_IDX
    DECF SPRITE_IDX, F
    BTFSS STATUS, 2
    GOTO ESR_LOOP
    RETURN

; DRAW/ERASE CAR
DRAW_CAR:
    CALL GET_LANE_X
    BANKSEL DRAW_PAGE
    MOVLF CAR_PAGE_TOP, DRAW_PAGE
    BANKSEL CAR_X
    MOVFFREG CAR_X, DRAW_X
    MOVLW CAR_TOP_0
    MOVWF FSR
    CALL DRAW_SPRITE_ROW
    BANKSEL DRAW_PAGE
    MOVLF CAR_PAGE_BOT, DRAW_PAGE
    BANKSEL CAR_X
    MOVFFREG CAR_X, DRAW_X
    MOVLW CAR_BOT_0
    MOVWF FSR
    CALL DRAW_SPRITE_ROW
    BANKSEL PLAYER_LANE
    MOVFFREG PLAYER_LANE, PREV_LANE
    RETURN

ERASE_CAR:
    CALL GET_PREV_LANE_X
    BANKSEL DRAW_PAGE
    MOVLF CAR_PAGE_TOP, DRAW_PAGE
    BANKSEL CAR_X
    MOVFFREG CAR_X, DRAW_X
    CALL ERASE_SPRITE_ROW
    BANKSEL DRAW_PAGE
    MOVLF CAR_PAGE_BOT, DRAW_PAGE
    BANKSEL CAR_X
    MOVFFREG CAR_X, DRAW_X
    CALL ERASE_SPRITE_ROW
    RETURN

; DRAW/ERASE ENEMY
DRAW_ENEMY:
    CALL GET_ENEMY_X
    BANKSEL CAR_X
    MOVFFREG CAR_X, DRAW_X
    MOVLW CAR_TOP_0
    MOVWF FSR
    CALL DRAW_SPRITE_ROW
    BANKSEL DRAW_PAGE
    INCF DRAW_PAGE, F
    BANKSEL CAR_X
    MOVFFREG CAR_X, DRAW_X
    MOVLW CAR_BOT_0
    MOVWF FSR
    CALL DRAW_SPRITE_ROW
    BANKSEL DRAW_PAGE
    DECF DRAW_PAGE, F
    RETURN

ERASE_ENEMY:
    CALL GET_ENEMY_X
    BANKSEL CAR_X
    MOVFFREG CAR_X, DRAW_X
    CALL ERASE_SPRITE_ROW
    BANKSEL DRAW_PAGE
    INCF DRAW_PAGE, F
    BANKSEL CAR_X
    MOVFFREG CAR_X, DRAW_X
    CALL ERASE_SPRITE_ROW
    BANKSEL DRAW_PAGE
    DECF DRAW_PAGE, F
    RETURN

; DRAW FUEL PICKUP
DRAW_FUEL_PICKUP:
    BANKSEL FUEL_LANE
    MOVFFREG FUEL_LANE, TEMP3
    CALL GET_ENEMY_X
    BANKSEL CAR_X
    MOVFFREG CAR_X, DRAW_X
    BANKSEL DISP_BYTE
    MOVLF 0x3E, DISP_BYTE
    CALL GLCD_PUT_BYTE
    BANKSEL DRAW_X
    INCF DRAW_X, F
    MOVLF 0x41, DISP_BYTE
    CALL GLCD_PUT_BYTE
    BANKSEL DRAW_X
    INCF DRAW_X, F
    MOVLF 0x5D, DISP_BYTE
    CALL GLCD_PUT_BYTE
    BANKSEL DRAW_X
    INCF DRAW_X, F
    MOVLF 0x41, DISP_BYTE
    CALL GLCD_PUT_BYTE
    BANKSEL DRAW_X
    INCF DRAW_X, F
    MOVLF 0x3E, DISP_BYTE
    CALL GLCD_PUT_BYTE
    RETURN

ERASE_FUEL_PICKUP:
    BANKSEL FUEL_LANE
    MOVFFREG FUEL_LANE, TEMP3
    CALL GET_ENEMY_X
    BANKSEL CAR_X
    MOVFFREG CAR_X, DRAW_X
    BANKSEL SPRITE_IDX
    MOVLF 5, SPRITE_IDX
EFUP_LOOP:
    BANKSEL DISP_BYTE
    MOVLF 0x00, DISP_BYTE
    CALL GLCD_PUT_BYTE
    BANKSEL DRAW_X
    INCF DRAW_X, F
    BANKSEL SPRITE_IDX
    DECF SPRITE_IDX, F
    BTFSS STATUS, 2
    GOTO EFUP_LOOP
    RETURN

; LFSR + RANDOM LANE
LFSR_STEP:
    BANKSEL LFSR_LO
    BTFSS LFSR_LO, 0
    GOTO LFSR_NO_FB
    BCF STATUS, 0
    RRF LFSR_HI, F
    RRF LFSR_LO, F
    MOVLW 0xD4
    XORWF LFSR_LO, F
    RETURN
LFSR_NO_FB:
    BCF STATUS, 0
    RRF LFSR_HI, F
    RRF LFSR_LO, F
    RETURN

GET_RANDOM_LANE:
    CALL LFSR_STEP
    BANKSEL LFSR_LO
    MOVF LFSR_LO, W
    ANDLW 0x03
    MOVWF TEMP3
    MOVLW 3
    SUBWF TEMP3, W
    BTFSS STATUS, 2
    RETURN
    BANKSEL TEMP3
    CLRF TEMP3
    RETURN

; SPAWN_ENEMY
SPAWN_ENEMY:
    BANKSEL ACTIVE_ENEMIES
    MOVLW MAX_ENEMIES
    SUBWF ACTIVE_ENEMIES, W
    BTFSC STATUS, 0
    RETURN

    CALL GET_RANDOM_LANE

    BANKSEL FUEL_LANE
    MOVLW ENEMY_INACTIVE
    SUBWF FUEL_LANE, W
    BTFSS STATUS, 2
    GOTO SE_ENEMY
    BANKSEL LFSR_HI
    BTFSS LFSR_HI, 3
    GOTO SE_ENEMY
    CALL GET_RANDOM_LANE
    BANKSEL FUEL_LANE
    MOVFFREG TEMP3, FUEL_LANE
    MOVLF ROAD_START_PAGE, FUEL_ROW
    BANKSEL DRAW_PAGE
    MOVLF ROAD_START_PAGE, DRAW_PAGE
    CALL DRAW_FUEL_PICKUP
    RETURN

SE_ENEMY:
    BANKSEL EN0_LANE
    MOVLW ENEMY_INACTIVE
    SUBWF EN0_LANE, W
    BTFSC STATUS, 2
    GOTO SE_SLOT0
    BANKSEL EN1_LANE
    MOVLW ENEMY_INACTIVE
    SUBWF EN1_LANE, W
    BTFSC STATUS, 2
    GOTO SE_SLOT1
    BANKSEL EN2_LANE
    MOVLW ENEMY_INACTIVE
    SUBWF EN2_LANE, W
    BTFSC STATUS, 2
    GOTO SE_SLOT2
    RETURN

SE_SLOT0:
    BANKSEL EN0_LANE
    MOVFFREG TEMP3, EN0_LANE
    MOVLF ROAD_START_PAGE, EN0_ROW
    GOTO SE_DONE
SE_SLOT1:
    BANKSEL EN1_LANE
    MOVFFREG TEMP3, EN1_LANE
    MOVLF ROAD_START_PAGE, EN1_ROW
    GOTO SE_DONE
SE_SLOT2:
    BANKSEL EN2_LANE
    MOVFFREG TEMP3, EN2_LANE
    MOVLF ROAD_START_PAGE, EN2_ROW

SE_DONE:
    BANKSEL ACTIVE_ENEMIES
    INCF ACTIVE_ENEMIES, F
    BANKSEL DRAW_PAGE
    MOVLF ROAD_START_PAGE, DRAW_PAGE
    CALL DRAW_ENEMY
    RETURN

; INCREMENT_SCORE + LEVEL UP
INCREMENT_SCORE:
    BANKSEL SCORE_LO
    INCF SCORE_LO, F
    BTFSC STATUS, 2
    INCF SCORE_HI, F
    MOVLF 1, HUD_DIRTY

    BANKSEL SCORE_LO
    MOVF SCORE_LO, W
    MOVWF TEMP1

    CMP_LIT TEMP1, SCORE_LVL5
    BTFSC STATUS, 0
    GOTO SET_LVL5
    CMP_LIT TEMP1, SCORE_LVL4
    BTFSC STATUS, 0
    GOTO SET_LVL4
    CMP_LIT TEMP1, SCORE_LVL3
    BTFSC STATUS, 0
    GOTO SET_LVL3
    CMP_LIT TEMP1, SCORE_LVL2
    BTFSC STATUS, 0
    GOTO SET_LVL2
    RETURN

SET_LVL2:
    BANKSEL LEVEL
    CMP_LIT LEVEL, 2
    BTFSC STATUS, 0
    RETURN
    MOVLF 2, LEVEL
    MOVLF SPEED_LVL2, SPEED_LEVEL
    RETURN
SET_LVL3:
    BANKSEL LEVEL
    CMP_LIT LEVEL, 3
    BTFSC STATUS, 0
    RETURN
    MOVLF 3, LEVEL
    MOVLF SPEED_LVL3, SPEED_LEVEL
    RETURN
SET_LVL4:
    BANKSEL LEVEL
    CMP_LIT LEVEL, 4
    BTFSC STATUS, 0
    RETURN
    MOVLF 4, LEVEL
    MOVLF SPEED_LVL4, SPEED_LEVEL
    RETURN
SET_LVL5:
    BANKSEL LEVEL
    CMP_LIT LEVEL, 5
    BTFSC STATUS, 0
    RETURN
    MOVLF 5, LEVEL
    MOVLF SPEED_LVL5, SPEED_LEVEL
    RETURN

; UPDATE_FUEL_PICKUP
UPDATE_FUEL_PICKUP:
    BANKSEL FUEL_LANE
    MOVLW ENEMY_INACTIVE
    SUBWF FUEL_LANE, W
    BTFSC STATUS, 2
    RETURN

    BANKSEL FUEL_ROW
    MOVFFREG FUEL_ROW, DRAW_PAGE
    CALL ERASE_FUEL_PICKUP

    BANKSEL FUEL_ROW
    INCF FUEL_ROW, F

    MOVLW CAR_PAGE_TOP
    SUBWF FUEL_ROW, W
    BTFSS STATUS, 2
    GOTO UFP_CHECK_GONE

    BANKSEL FUEL_LANE
    MOVF FUEL_LANE, W
    BANKSEL PLAYER_LANE
    SUBWF PLAYER_LANE, W
    BTFSS STATUS, 2
    GOTO UFP_CHECK_GONE

    BANKSEL FUEL_LEVEL
    MOVLW 30
    ADDWF FUEL_LEVEL, F
    MOVLW FUEL_MAX
    SUBWF FUEL_LEVEL, W
    BTFSS STATUS, 0
    GOTO UFP_COLLECTED
    MOVLF FUEL_MAX, FUEL_LEVEL
UFP_COLLECTED:
    MOVLF ENEMY_INACTIVE, FUEL_LANE
    MOVLF 1, HUD_DIRTY
    RETURN

UFP_CHECK_GONE:
    BANKSEL FUEL_ROW
    MOVLW 8
    SUBWF FUEL_ROW, W
    BTFSC STATUS, 0
    GOTO UFP_GONE
    BANKSEL FUEL_ROW
    MOVFFREG FUEL_ROW, DRAW_PAGE
    CALL DRAW_FUEL_PICKUP
    RETURN
UFP_GONE:
    MOVLF ENEMY_INACTIVE, FUEL_LANE
    RETURN

; UPDATE_ENEMIES
UPDATE_ENEMIES:
    BANKSEL EN0_LANE
    MOVLW ENEMY_INACTIVE
    SUBWF EN0_LANE, W
    BTFSC STATUS, 2
    GOTO UE_SKIP0
    BANKSEL EN0_ROW
    MOVFFREG EN0_ROW, DRAW_PAGE
    BANKSEL EN0_LANE
    MOVFFREG EN0_LANE, TEMP3
    CALL ERASE_ENEMY
    BANKSEL EN0_ROW
    INCF EN0_ROW, F
    MOVLW CAR_PAGE_TOP
    SUBWF EN0_ROW, W
    BTFSC STATUS, 0
    CALL CHECK_COLLISION
    BANKSEL EN0_ROW
    MOVLW 8
    SUBWF EN0_ROW, W
    BTFSS STATUS, 0
    GOTO UE_DRAW0
    MOVLF ENEMY_INACTIVE, EN0_LANE
    BANKSEL ACTIVE_ENEMIES
    MOVF ACTIVE_ENEMIES, F
    BTFSS STATUS, 2
    DECF ACTIVE_ENEMIES, F
    CALL INCREMENT_SCORE
    GOTO UE_SKIP0
UE_DRAW0:
    BANKSEL EN0_ROW
    MOVFFREG EN0_ROW, DRAW_PAGE
    BANKSEL EN0_LANE
    MOVFFREG EN0_LANE, TEMP3
    CALL DRAW_ENEMY
UE_SKIP0:

    BANKSEL EN1_LANE
    MOVLW ENEMY_INACTIVE
    SUBWF EN1_LANE, W
    BTFSC STATUS, 2
    GOTO UE_SKIP1
    BANKSEL EN1_ROW
    MOVFFREG EN1_ROW, DRAW_PAGE
    BANKSEL EN1_LANE
    MOVFFREG EN1_LANE, TEMP3
    CALL ERASE_ENEMY
    BANKSEL EN1_ROW
    INCF EN1_ROW, F
    MOVLW CAR_PAGE_TOP
    SUBWF EN1_ROW, W
    BTFSC STATUS, 0
    CALL CHECK_COLLISION
    BANKSEL EN1_ROW
    MOVLW 8
    SUBWF EN1_ROW, W
    BTFSS STATUS, 0
    GOTO UE_DRAW1
    MOVLF ENEMY_INACTIVE, EN1_LANE
    BANKSEL ACTIVE_ENEMIES
    MOVF ACTIVE_ENEMIES, F
    BTFSS STATUS, 2
    DECF ACTIVE_ENEMIES, F
    CALL INCREMENT_SCORE
    GOTO UE_SKIP1
UE_DRAW1:
    BANKSEL EN1_ROW
    MOVFFREG EN1_ROW, DRAW_PAGE
    BANKSEL EN1_LANE
    MOVFFREG EN1_LANE, TEMP3
    CALL DRAW_ENEMY
UE_SKIP1:

    BANKSEL EN2_LANE
    MOVLW ENEMY_INACTIVE
    SUBWF EN2_LANE, W
    BTFSC STATUS, 2
    GOTO UE_SKIP2
    BANKSEL EN2_ROW
    MOVFFREG EN2_ROW, DRAW_PAGE
    BANKSEL EN2_LANE
    MOVFFREG EN2_LANE, TEMP3
    CALL ERASE_ENEMY
    BANKSEL EN2_ROW
    INCF EN2_ROW, F
    MOVLW CAR_PAGE_TOP
    SUBWF EN2_ROW, W
    BTFSC STATUS, 0
    CALL CHECK_COLLISION
    BANKSEL EN2_ROW
    MOVLW 8
    SUBWF EN2_ROW, W
    BTFSS STATUS, 0
    GOTO UE_DRAW2
    MOVLF ENEMY_INACTIVE, EN2_LANE
    BANKSEL ACTIVE_ENEMIES
    MOVF ACTIVE_ENEMIES, F
    BTFSS STATUS, 2
    DECF ACTIVE_ENEMIES, F
    CALL INCREMENT_SCORE
    GOTO UE_SKIP2
UE_DRAW2:
    BANKSEL EN2_ROW
    MOVFFREG EN2_ROW, DRAW_PAGE
    BANKSEL EN2_LANE
    MOVFFREG EN2_LANE, TEMP3
    CALL DRAW_ENEMY
UE_SKIP2:
    RETURN

; DO_GAME_OVER
DO_GAME_OVER:
    BANKSEL GAME_STATE
    MOVLF STATE_GAMEOVER, GAME_STATE

    CALL CHECK_AND_SAVE_HISCORE
    CALL DRAW_GAMEOVER_SCREEN
    RETURN

; MAIN_LOOP
MAIN_LOOP:
    BANKSEL ISR_FLAGS
    BTFSS ISR_FLAGS, FLAG_TICK
    GOTO MAIN_LOOP
    BCF ISR_FLAGS, FLAG_TICK

    CALL BUTTON_SCAN

    BANKSEL GAME_STATE
    CMP_LIT GAME_STATE, STATE_PLAY
    BTFSS STATUS, 2
    GOTO ML_FSM

    BANKSEL GAME_TICK
    INCF GAME_TICK, F
    BANKSEL SPEED_LEVEL
    MOVF SPEED_LEVEL, W
    BANKSEL GAME_TICK
    SUBWF GAME_TICK, W
    BTFSS STATUS, 2
    GOTO ML_HUD_CHECK

    BANKSEL GAME_TICK
    CLRF GAME_TICK
    BANKSEL ROAD_SCROLL
    INCF ROAD_SCROLL, F
    MOVLW 8
    SUBWF ROAD_SCROLL, W
    BTFSS STATUS, 2
    GOTO ML_SCROLL
    BANKSEL ROAD_SCROLL
    CLRF ROAD_SCROLL

ML_SCROLL:
    BANKSEL FUEL_TICK
    DECF FUEL_TICK, F
    BTFSS STATUS, 2
    GOTO ML_NO_FUEL
    MOVLF FUEL_DEC_INT, FUEL_TICK
    BANKSEL FUEL_LEVEL
    MOVF FUEL_LEVEL, F
    BTFSC STATUS, 2
    GOTO ML_DO_GAME_OVER
    DECF FUEL_LEVEL, F
    MOVLF 1, HUD_DIRTY
ML_NO_FUEL:

    BANKSEL SPAWN_TIMER
    DECF SPAWN_TIMER, F
    BTFSS STATUS, 2
    GOTO ML_NO_SPAWN
    BANKSEL LEVEL
    MOVF LEVEL, W
    MOVWF TEMP1
    CMP_LIT TEMP1, 5
    BTFSC STATUS, 2
    GOTO ML_SP5
    CMP_LIT TEMP1, 4
    BTFSC STATUS, 2
    GOTO ML_SP4
    CMP_LIT TEMP1, 3
    BTFSC STATUS, 2
    GOTO ML_SP3
    CMP_LIT TEMP1, 2
    BTFSC STATUS, 2
    GOTO ML_SP2
    MOVLF SPAWN_LVL1, SPAWN_TIMER
    GOTO ML_DO_SPAWN
ML_SP2: MOVLF SPAWN_LVL2, SPAWN_TIMER
    GOTO ML_DO_SPAWN
ML_SP3: MOVLF SPAWN_LVL3, SPAWN_TIMER
    GOTO ML_DO_SPAWN
ML_SP4: MOVLF SPAWN_LVL4, SPAWN_TIMER
    GOTO ML_DO_SPAWN
ML_SP5: MOVLF SPAWN_LVL5, SPAWN_TIMER
ML_DO_SPAWN:
    CALL SPAWN_ENEMY
ML_NO_SPAWN:

    CALL UPDATE_FUEL_PICKUP
    CALL UPDATE_ENEMIES
    BANKSEL ISR_FLAGS
    BTFSC ISR_FLAGS, FLAG_COLLISION
    GOTO ML_DO_GAME_OVER
    CALL DRAW_ROAD
    CALL DRAW_CAR
    GOTO ML_HUD_CHECK
ML_DO_GAME_OVER:
    BCF ISR_FLAGS, FLAG_COLLISION
    BANKSEL HUD_DIRTY
    CLRF HUD_DIRTY
    CALL DO_GAME_OVER
    GOTO MAIN_LOOP

ML_HUD_CHECK:
    BANKSEL HUD_DIRTY
    MOVF HUD_DIRTY, F
    BTFSS STATUS, 2
    CALL DRAW_HUD

ML_FSM:
    BANKSEL GAME_STATE
    CMP_LIT GAME_STATE, STATE_PLAY
    BTFSC STATUS, 2
    GOTO FSM_PLAY

    CMP_LIT GAME_STATE, STATE_PAUSE
    BTFSC STATUS, 2
    GOTO FSM_PAUSE

    CMP_LIT GAME_STATE, STATE_GAMEOVER
    BTFSC STATUS, 2
    GOTO FSM_GAMEOVER

    CMP_LIT GAME_STATE, STATE_MENU
    BTFSC STATUS, 2
    GOTO FSM_MENU

    MOVLF STATE_MENU, GAME_STATE
    GOTO MAIN_LOOP

; FSM STATES
FSM_PLAY:
    BANKSEL BTN_EVENT
    BTFSS BTN_EVENT, BTN_SEL_B
    GOTO FP_LEFT
    BANKSEL GAME_STATE
    MOVLF STATE_PAUSE, GAME_STATE
    GOTO MAIN_LOOP
FP_LEFT:
    BANKSEL BTN_EVENT
    BTFSS BTN_EVENT, BTN_LEFT_B
    GOTO FP_RIGHT
    BANKSEL PLAYER_LANE
    MOVF PLAYER_LANE, F
    BTFSC STATUS, 2
    GOTO MAIN_LOOP
    CALL ERASE_CAR
    BANKSEL PLAYER_LANE
    DECF PLAYER_LANE, F
    CALL DRAW_CAR
    GOTO MAIN_LOOP
FP_RIGHT:
    BANKSEL BTN_EVENT
    BTFSS BTN_EVENT, BTN_RIGHT_B
    GOTO MAIN_LOOP
    BANKSEL PLAYER_LANE
    CMP_LIT PLAYER_LANE, 2
    BTFSC STATUS, 2
    GOTO MAIN_LOOP
    CALL ERASE_CAR
    BANKSEL PLAYER_LANE
    INCF PLAYER_LANE, F
    CALL DRAW_CAR
    GOTO MAIN_LOOP

FSM_PAUSE:
    BANKSEL BTN_EVENT
    BTFSS BTN_EVENT, BTN_SEL_B
    GOTO MAIN_LOOP
    BANKSEL GAME_STATE
    MOVLF STATE_PLAY, GAME_STATE
    GOTO MAIN_LOOP

FSM_GAMEOVER:
    BANKSEL NEW_BEST
    MOVF NEW_BEST, F
    BTFSC STATUS, 2
    GOTO FGO_BTN
    BANKSEL MENU_FLASH
    INCF MENU_FLASH, F
    MOVLW 39
    SUBWF MENU_FLASH, W
    BTFSS STATUS, 2
    GOTO FGO_BTN
    CLRF MENU_FLASH
    BANKSEL BLINK_FLAG
    INCF BLINK_FLAG, F
    BTFSS BLINK_FLAG, 0
    GOTO FGO_CLEAR_NR
    CALL DRAW_NEW_RECORD
    GOTO FGO_BTN
FGO_CLEAR_NR:
    MOVLF 4, DRAW_PAGE
    CALL DRAW_CLEAR_ROW

FGO_BTN:
    BANKSEL BTN_STATE
    BTFSS BTN_STATE, BTN_SEL_B
    GOTO MAIN_LOOP
    BANKSEL GAME_STATE
    MOVLF STATE_MENU, GAME_STATE
    CALL DRAW_MENU
    GOTO MAIN_LOOP  

FSM_MENU:
    BANKSEL MENU_FLASH
    INCF MENU_FLASH, F
    MOVLW 12
    SUBWF MENU_FLASH, W
    BTFSS STATUS, 2
    GOTO FM_BTN
    CLRF MENU_FLASH
    BANKSEL BLINK_FLAG
    INCF BLINK_FLAG, F
    BTFSS BLINK_FLAG, 0
    GOTO FM_FLASH_CLEAR
    CALL DRAW_MENU_CURSOR
    GOTO FM_BTN
FM_FLASH_CLEAR:
    MOVLF 6, DRAW_PAGE
    MOVLF 46, DRAW_X
    MOVLF FC_SPC, TEMP1
    CALL DRAW_CHAR

FM_BTN:
    BANKSEL BTN_EVENT
    BTFSS BTN_EVENT, BTN_SEL_B
    GOTO MAIN_LOOP
    CALL GAME_RESET
    GOTO MAIN_LOOP

