; GLCD DRIVER
GLCD_INIT:
    GLCD_RST_LOW
    MOVLW 1
    CALL DELAY_TICKS
    GLCD_RST_HIGH
    MOVLW 1
    CALL DELAY_TICKS
    GLCD_CS1_ON
    MOVLW GLCD_ON
    CALL GLCD_WRITE_CMD
    MOVLW GLCD_STARTLINE
    CALL GLCD_WRITE_CMD
    MOVLW GLCD_SET_PAGE
    CALL GLCD_WRITE_CMD
    MOVLW GLCD_SET_Y
    CALL GLCD_WRITE_CMD
    GLCD_CS2_ON
    MOVLW GLCD_ON
    CALL GLCD_WRITE_CMD
    MOVLW GLCD_STARTLINE
    CALL GLCD_WRITE_CMD
    MOVLW GLCD_SET_PAGE
    CALL GLCD_WRITE_CMD
    MOVLW GLCD_SET_Y
    CALL GLCD_WRITE_CMD
    CALL GLCD_CLEAR_ALL
    GLCD_CS_NONE
    RETURN

GLCD_WRITE_CMD:
    BANKSEL DISP_TEMP
    MOVWF DISP_TEMP
    GLCD_CMD_MODE
    GLCD_WRITE_MODE
    BANKSEL PORTD
    MOVF DISP_TEMP, W
    MOVWF PORTD
    GLCD_EN_PULSE
    RETURN

GLCD_WRITE_DATA:
    BANKSEL DISP_TEMP
    MOVWF DISP_TEMP
    GLCD_DATA_MODE
    GLCD_WRITE_MODE
    BANKSEL PORTD
    MOVF DISP_TEMP, W
    MOVWF PORTD
    GLCD_EN_PULSE
    RETURN

GLCD_CLEAR_HALF:
    BANKSEL DISP_PAGE
    CLRF DISP_PAGE
CLRH_PAGE:
    BANKSEL DISP_PAGE
    MOVF DISP_PAGE, W
    IORLW GLCD_SET_PAGE
    CALL GLCD_WRITE_CMD
    MOVLW GLCD_SET_Y
    CALL GLCD_WRITE_CMD
    BANKSEL DISP_COL
    CLRF DISP_COL
CLRH_COL:
    MOVLW 0x00
    CALL GLCD_WRITE_DATA
    BANKSEL DISP_COL
    INCF DISP_COL, F
    MOVLW 64
    SUBWF DISP_COL, W
    BTFSS STATUS, 2
    GOTO CLRH_COL
    BANKSEL DISP_PAGE
    INCF DISP_PAGE, F
    MOVLW 8
    SUBWF DISP_PAGE, W
    BTFSS STATUS, 2
    GOTO CLRH_PAGE
    RETURN

GLCD_CLEAR_ALL:
    GLCD_CS1_ON
    CALL GLCD_CLEAR_HALF
    GLCD_CS2_ON
    CALL GLCD_CLEAR_HALF
    GLCD_CS_NONE
    RETURN

GLCD_PUT_BYTE:
    BANKSEL DRAW_X
    MOVLW 64
    SUBWF DRAW_X, W
    BTFSS STATUS, 0
    GOTO GPB_CS1
    GLCD_CS2_ON
    BANKSEL DRAW_X
    MOVLW 64
    SUBWF DRAW_X, W
    GOTO GPB_COL
GPB_CS1:
    GLCD_CS1_ON
    BANKSEL DRAW_X
    MOVF DRAW_X, W
GPB_COL:
    IORLW GLCD_SET_Y
    CALL GLCD_WRITE_CMD
    BANKSEL DRAW_PAGE
    MOVF DRAW_PAGE, W
    IORLW GLCD_SET_PAGE
    CALL GLCD_WRITE_CMD
    BANKSEL DISP_BYTE
    MOVF DISP_BYTE, W
    CALL GLCD_WRITE_DATA
    GLCD_CS_NONE
    RETURN

DRAW_SOLID_ROW:
    BANKSEL DRAW_X
    CLRF DRAW_X
DSR2_LOOP:
    BANKSEL DISP_BYTE
    MOVLF 0xFF, DISP_BYTE
    CALL GLCD_PUT_BYTE
    BANKSEL DRAW_X
    INCF DRAW_X, F
    MOVLW 128
    SUBWF DRAW_X, W
    BTFSS STATUS, 2
    GOTO DSR2_LOOP
    RETURN

DRAW_CLEAR_ROW:
    BANKSEL DRAW_X
    CLRF DRAW_X
DCR_LOOP:
    BANKSEL DISP_BYTE
    MOVLF 0x00, DISP_BYTE
    CALL GLCD_PUT_BYTE
    BANKSEL DRAW_X
    INCF DRAW_X, F
    MOVLW 128
    SUBWF DRAW_X, W
    BTFSS STATUS, 2
    GOTO DCR_LOOP
    RETURN

; DELAY_TICKS
DELAY_TICKS:
    BANKSEL TEMP1
    MOVWF TEMP1
    BANKSEL TICK_COUNTER
    MOVF TICK_COUNTER, W
    BANKSEL TEMP1
    ADDWF TEMP1, F
DLY_WAIT:
    BANKSEL TICK_COUNTER
    MOVF TICK_COUNTER, W
    BANKSEL TEMP1
    SUBWF TEMP1, W
    BTFSS STATUS, 2
    GOTO DLY_WAIT
    BCF ISR_FLAGS, FLAG_TICK
    RETURN

