; GPIO_INIT
GPIO_INIT:
    BANKSEL ADCON1
    MOVLW 0x06
    MOVWF ADCON1
    BANKSEL TRISA
    MOVLW 0b00000111
    MOVWF TRISA
    BANKSEL TRISB
    MOVLW 0b00000000
    MOVWF TRISB
    BANKSEL TRISC
    MOVLW 0b11111011
    MOVWF TRISC
    BANKSEL TRISD
    MOVLW 0b00000000
    MOVWF TRISD
    BANKSEL PORTA
    CLRF PORTA
    CLRF PORTB
    CLRF PORTC
    CLRF PORTD
    BSF PORTB, GLCD_RST_B
    BANKSEL BTN_STATE
    MOVLF 0x07, BTN_PREV
    MOVLF 0x07, BTN_STATE
    CLRF BTN_EVENT
    RETURN

; BUTTON_SCAN
BUTTON_SCAN:
    BANKSEL PORTA
    MOVF PORTA, W
    ANDLW BTN_MASK_C
    XORLW BTN_MASK_C
    BANKSEL TEMP1
    MOVWF TEMP1
    MOVF BTN_PREV, W
    XORWF TEMP1, W
    MOVWF TEMP2
    MOVF TEMP1, W
    ANDWF TEMP2, W
    MOVWF BTN_EVENT
    MOVFFREG TEMP1, BTN_STATE
    MOVFFREG TEMP1, BTN_PREV
    RETURN

