ISR_HANDLER:
    MOVWF W_TEMP
    SWAPF STATUS, W
    MOVWF STATUS_TEMP
    BCF STATUS, 5
    BCF STATUS, 6
    MOVF PCLATH, W
    MOVWF PCLATH_TEMP
    CLRF PCLATH
    BTFSC INTCON, 2
    CALL TIMER0_ISR
    MOVF PCLATH_TEMP, W
    MOVWF PCLATH
    SWAPF STATUS_TEMP, W
    MOVWF STATUS
    SWAPF W_TEMP, F
    SWAPF W_TEMP, W
    RETFIE

TIMER0_ISR:
    MOVLF TMR0_RELOAD, TMR0
    INCF TICK_COUNTER, F
    BSF ISR_FLAGS, FLAG_TICK
    BCF INTCON, 2
    RETURN

