; Racing Car - PIC16F877A KS0108 GLCD
; College Project
; By Ayush and Yajat

    PROCESSOR 16F877A
    #include    <xc.inc>

    config FOSC = HS
    config WDTE = OFF
    config PWRTE = ON
    config BOREN = ON
    config LVP = OFF
    config CPD = OFF
    config WRT = OFF
    config CP = OFF

; RAM MAP
W_TEMP EQU 0x70
STATUS_TEMP EQU 0x71
PCLATH_TEMP EQU 0x6C

CAR_TOP_0 EQU 0x72
CAR_TOP_1 EQU 0x73
CAR_TOP_2 EQU 0x74
CAR_TOP_3 EQU 0x75
CAR_TOP_4 EQU 0x76
CAR_TOP_5 EQU 0x77
CAR_TOP_6 EQU 0x78
CAR_TOP_7 EQU 0x79
CAR_TOP_8 EQU 0x7A
CAR_TOP_9 EQU 0x7B
CAR_TOP_A EQU 0x7C
CAR_TOP_B EQU 0x7D

GAME_STATE EQU 0x20
LEVEL EQU 0x21
ISR_FLAGS EQU 0x22
TICK_COUNTER EQU 0x23
GAME_TICK EQU 0x24
PLAYER_LANE EQU 0x25
PREV_LANE EQU 0x26
FUEL_LEVEL EQU 0x27
FUEL_DEC_TIMER EQU 0x28
SCORE_LO EQU 0x29
SCORE_HI EQU 0x2A
SPEED_LEVEL EQU 0x2B
ROAD_SCROLL EQU 0x2C
DRAW_X EQU 0x2D
DRAW_PAGE EQU 0x2E
DISP_BYTE EQU 0x2F
DISP_TEMP EQU 0x30
DISP_COL EQU 0x31
DISP_PAGE EQU 0x32
SPRITE_IDX EQU 0x33
CAR_X EQU 0x34
TEMP1 EQU 0x35
TEMP2 EQU 0x36
TEMP3 EQU 0x37
LOOP_CNT EQU 0x38
BTN_STATE EQU 0x39
BTN_PREV EQU 0x3A
BTN_EVENT EQU 0x3B
LFSR_LO EQU 0x3C
LFSR_HI EQU 0x3D
SPAWN_TIMER EQU 0x3E
FUEL_TICK EQU 0x3F

EN0_LANE EQU 0x50
EN0_ROW EQU 0x51
EN1_LANE EQU 0x52
EN1_ROW EQU 0x53
EN2_LANE EQU 0x54
EN2_ROW EQU 0x55
ACTIVE_ENEMIES EQU 0x56
FUEL_LANE EQU 0x57
FUEL_ROW EQU 0x58
SCORE_DISP EQU 0x59
HUD_DIRTY EQU 0x5A
PREV_FUEL EQU 0x5B

HISCORE_LO EQU 0x5C
HISCORE_HI EQU 0x5D
NEW_BEST EQU 0x5E
MENU_FLASH EQU 0x5F

CAR_BOT_0 EQU 0x60
CAR_BOT_1 EQU 0x61
CAR_BOT_2 EQU 0x62
CAR_BOT_3 EQU 0x63
CAR_BOT_4 EQU 0x64
CAR_BOT_5 EQU 0x65
CAR_BOT_6 EQU 0x66
CAR_BOT_7 EQU 0x67
CAR_BOT_8 EQU 0x68
CAR_BOT_9 EQU 0x69
CAR_BOT_A EQU 0x6A
CAR_BOT_B EQU 0x6B

; CONSTANTS
STATE_MENU EQU 0
STATE_PLAY EQU 1
STATE_PAUSE EQU 2
STATE_GAMEOVER EQU 3

FUEL_MAX EQU 100
FUEL_DEC_INT EQU 10
SPEED_LVL1 EQU 8
SPEED_LVL2 EQU 6
SPEED_LVL3 EQU 5
SPEED_LVL4 EQU 3
SPEED_LVL5 EQU 2
SCORE_LVL2 EQU 10
SCORE_LVL3 EQU 25
SCORE_LVL4 EQU 50
SCORE_LVL5 EQU 80
SPAWN_LVL1 EQU 5
SPAWN_LVL2 EQU 4
SPAWN_LVL3 EQU 3
SPAWN_LVL4 EQU 3
SPAWN_LVL5 EQU 2

TMR0_RELOAD EQU 6
FLAG_TICK EQU 0
FLAG_COLLISION EQU 1
BTN_LEFT_B EQU 0
BTN_RIGHT_B EQU 1
BTN_SEL_B EQU 2
BTN_MASK_C EQU 0x07

GLCD_CS1_B EQU 0
GLCD_CS2_B EQU 1
GLCD_DI_B EQU 2
GLCD_RW_B EQU 3
GLCD_EN_B EQU 4
GLCD_RST_B EQU 5
GLCD_ON EQU 0x3F
GLCD_SET_Y EQU 0x40
GLCD_SET_PAGE EQU 0xB8
GLCD_STARTLINE EQU 0xC0

LANE0_X EQU 1
LANE1_X EQU 44
LANE2_X EQU 87
CAR_OFF EQU 15
DIV1_COL EQU 42
DIV2_COL EQU 85
CAR_PAGE_TOP EQU 5
CAR_PAGE_BOT EQU 6
CAR_WIDTH EQU 12
ROAD_START_PAGE EQU 1
ENEMY_INACTIVE EQU 0xFF
MAX_ENEMIES EQU 3
HUD_PAGE EQU 0
FUEL_BAR_W EQU 40

FC_SPC EQU 0
FC_GT EQU 1
FC_A EQU 2
FC_B EQU 3
FC_C EQU 4
FC_D EQU 5
FC_E EQU 6
FC_F EQU 7
FC_G EQU 8
FC_H EQU 9
FC_I EQU 10
FC_J EQU 11
FC_K EQU 12
FC_L EQU 13
FC_M EQU 14
FC_N EQU 15
FC_O EQU 16
FC_P EQU 17
FC_Q EQU 18
FC_R EQU 19
FC_S EQU 20
FC_T EQU 21
FC_U EQU 22
FC_V EQU 23
FC_W EQU 24
FC_X EQU 25
FC_Y EQU 26
FC_Z EQU 27
FC_0 EQU 28
FC_1 EQU 29
FC_2 EQU 30
FC_3 EQU 31
FC_4 EQU 32
FC_5 EQU 33
FC_6 EQU 34
FC_7 EQU 35
FC_8 EQU 36
FC_9 EQU 37
FC_COL EQU 38
FC_EQ EQU 39
FC_EX EQU 40
FC_DASH EQU 41

BLINK_FLAG EQU 0x40

EE_HISCORE_LO EQU 0x00
EE_HISCORE_HI EQU 0x01
EE_SENTINEL EQU 0x02
EE_VALID EQU 0xA5

; MACROS
MOVLF MACRO LIT, DEST
        MOVLW LIT
        MOVWF DEST
        ENDM

MOVFFREG MACRO SRC, DEST
        MOVF SRC, W
        MOVWF DEST
        ENDM

CLR16 MACRO LO, HI
        CLRF LO
        CLRF HI
        ENDM

CMP_LIT MACRO REG, LIT
        MOVLW LIT
        SUBWF REG, W
        ENDM

GLCD_CS1_ON MACRO
        BSF PORTB, GLCD_CS1_B
        BCF PORTB, GLCD_CS2_B
        ENDM

GLCD_CS2_ON MACRO
        BCF PORTB, GLCD_CS1_B
        BSF PORTB, GLCD_CS2_B
        ENDM

GLCD_CS_NONE MACRO
        BCF PORTB, GLCD_CS1_B
        BCF PORTB, GLCD_CS2_B
        ENDM

GLCD_CMD_MODE MACRO
        BCF PORTB, GLCD_DI_B
        ENDM

GLCD_DATA_MODE MACRO
        BSF PORTB, GLCD_DI_B
        ENDM

GLCD_WRITE_MODE MACRO
        BCF PORTB, GLCD_RW_B
        ENDM

GLCD_EN_PULSE MACRO
        BSF PORTB, GLCD_EN_B
        NOP
        NOP
        NOP
        BCF PORTB, GLCD_EN_B
        NOP
        ENDM

GLCD_RST_LOW MACRO
        BCF PORTB, GLCD_RST_B
        ENDM

GLCD_RST_HIGH MACRO
        BSF PORTB, GLCD_RST_B
        ENDM

; VECTORS
PSECT resetVec, class=CODE, delta=2, abs, ovrld
    ORG 0x0000
    GOTO SYSTEM_INIT

PSECT isrVec, class=CODE, delta=2, abs, ovrld
    ORG 0x0004
    GOTO ISR_HANDLER

; MAIN CODE
PSECT mainCode, class=CODE, delta=2

; SYSTEM_INIT
SYSTEM_INIT:
    BANKSEL GAME_STATE
    MOVLW 0x20
    MOVWF FSR
CLR_LOOP:
    CLRF INDF
    INCF FSR, F
    MOVLW 0x6C
    SUBWF FSR, W
    BTFSS STATUS, 2
    GOTO CLR_LOOP

    CALL GPIO_INIT
    CALL TIMER0_INIT
    BSF INTCON, 7

    CALL LOAD_SPRITES
    CALL EEPROM_LOAD_HISCORE
    CALL GLCD_INIT

    BANKSEL GAME_STATE
    MOVLF STATE_MENU, GAME_STATE

    CALL DRAW_BOOT_SPLASH
    CALL DRAW_MENU
    GOTO MAIN_LOOP

; TIMER0_INIT
TIMER0_INIT:
    BANKSEL OPTION_REG
    MOVLW 0b11000111
    MOVWF OPTION_REG
    BANKSEL TMR0
    CLRF TMR0
    MOVLF TMR0_RELOAD, TMR0
    BANKSEL TICK_COUNTER
    CLRF TICK_COUNTER
    CLRF GAME_TICK
    CLRF ISR_FLAGS
    BSF INTCON, 5
    RETURN


#include "interrupt.asm"
#include "sprites.asm"
#include "eeprom.asm"
#include "input.asm"
#include "glcd.asm"
#include "collision.asm"
#include "game.asm"
#include "font.asm"
    END
