; Racing Car - PIC16F877A KS0108 GLCD
; College Project
; By Ayush and Yajat

    PROCESSOR 16F877A
    #include    <xc.inc>

    config FOSC = HS
    config WDTE = OFF
    config PWRTE = ON
    config BOREN = ON
    config LVP = OFF
    config CPD = OFF
    config WRT = OFF
    config CP = OFF

; RAM MAP
W_TEMP EQU 0x70
STATUS_TEMP EQU 0x71
PCLATH_TEMP EQU 0x6C

CAR_TOP_0 EQU 0x72
CAR_TOP_1 EQU 0x73
CAR_TOP_2 EQU 0x74
CAR_TOP_3 EQU 0x75
CAR_TOP_4 EQU 0x76
CAR_TOP_5 EQU 0x77
CAR_TOP_6 EQU 0x78
CAR_TOP_7 EQU 0x79
CAR_TOP_8 EQU 0x7A
CAR_TOP_9 EQU 0x7B
CAR_TOP_A EQU 0x7C
CAR_TOP_B EQU 0x7D

GAME_STATE EQU 0x20
LEVEL EQU 0x21
ISR_FLAGS EQU 0x22
TICK_COUNTER EQU 0x23
GAME_TICK EQU 0x24
PLAYER_LANE EQU 0x25
PREV_LANE EQU 0x26
FUEL_LEVEL EQU 0x27
FUEL_DEC_TIMER EQU 0x28
SCORE_LO EQU 0x29
SCORE_HI EQU 0x2A
SPEED_LEVEL EQU 0x2B
ROAD_SCROLL EQU 0x2C
DRAW_X EQU 0x2D
DRAW_PAGE EQU 0x2E
DISP_BYTE EQU 0x2F
DISP_TEMP EQU 0x30
DISP_COL EQU 0x31
DISP_PAGE EQU 0x32
SPRITE_IDX EQU 0x33
CAR_X EQU 0x34
TEMP1 EQU 0x35
TEMP2 EQU 0x36
TEMP3 EQU 0x37
LOOP_CNT EQU 0x38
BTN_STATE EQU 0x39
BTN_PREV EQU 0x3A
BTN_EVENT EQU 0x3B
LFSR_LO EQU 0x3C
LFSR_HI EQU 0x3D
SPAWN_TIMER EQU 0x3E
FUEL_TICK EQU 0x3F

EN0_LANE EQU 0x50
EN0_ROW EQU 0x51
EN1_LANE EQU 0x52
EN1_ROW EQU 0x53
EN2_LANE EQU 0x54
EN2_ROW EQU 0x55
ACTIVE_ENEMIES EQU 0x56
FUEL_LANE EQU 0x57
FUEL_ROW EQU 0x58
SCORE_DISP EQU 0x59
HUD_DIRTY EQU 0x5A
PREV_FUEL EQU 0x5B

HISCORE_LO EQU 0x5C
HISCORE_HI EQU 0x5D
NEW_BEST EQU 0x5E
MENU_FLASH EQU 0x5F

CAR_BOT_0 EQU 0x60
CAR_BOT_1 EQU 0x61
CAR_BOT_2 EQU 0x62
CAR_BOT_3 EQU 0x63
CAR_BOT_4 EQU 0x64
CAR_BOT_5 EQU 0x65
CAR_BOT_6 EQU 0x66
CAR_BOT_7 EQU 0x67
CAR_BOT_8 EQU 0x68
CAR_BOT_9 EQU 0x69
CAR_BOT_A EQU 0x6A
CAR_BOT_B EQU 0x6B

; CONSTANTS
STATE_MENU EQU 0
STATE_PLAY EQU 1
STATE_PAUSE EQU 2
STATE_GAMEOVER EQU 3

FUEL_MAX EQU 100
FUEL_DEC_INT EQU 10
SPEED_LVL1 EQU 8
SPEED_LVL2 EQU 6
SPEED_LVL3 EQU 5
SPEED_LVL4 EQU 3
SPEED_LVL5 EQU 2
SCORE_LVL2 EQU 10
SCORE_LVL3 EQU 25
SCORE_LVL4 EQU 50
SCORE_LVL5 EQU 80
SPAWN_LVL1 EQU 5
SPAWN_LVL2 EQU 4
SPAWN_LVL3 EQU 3
SPAWN_LVL4 EQU 3
SPAWN_LVL5 EQU 2

TMR0_RELOAD EQU 6
FLAG_TICK EQU 0
FLAG_COLLISION EQU 1
BTN_LEFT_B EQU 0
BTN_RIGHT_B EQU 1
BTN_SEL_B EQU 2
BTN_MASK_C EQU 0x07

GLCD_CS1_B EQU 0
GLCD_CS2_B EQU 1
GLCD_DI_B EQU 2
GLCD_RW_B EQU 3
GLCD_EN_B EQU 4
GLCD_RST_B EQU 5
GLCD_ON EQU 0x3F
GLCD_SET_Y EQU 0x40
GLCD_SET_PAGE EQU 0xB8
GLCD_STARTLINE EQU 0xC0

LANE0_X EQU 1
LANE1_X EQU 44
LANE2_X EQU 87
CAR_OFF EQU 15
DIV1_COL EQU 42
DIV2_COL EQU 85
CAR_PAGE_TOP EQU 5
CAR_PAGE_BOT EQU 6
CAR_WIDTH EQU 12
ROAD_START_PAGE EQU 1
ENEMY_INACTIVE EQU 0xFF
MAX_ENEMIES EQU 3
HUD_PAGE EQU 0
FUEL_BAR_W EQU 40

FC_SPC EQU 0
FC_GT EQU 1
FC_A EQU 2
FC_B EQU 3
FC_C EQU 4
FC_D EQU 5
FC_E EQU 6
FC_F EQU 7
FC_G EQU 8
FC_H EQU 9
FC_I EQU 10
FC_J EQU 11
FC_K EQU 12
FC_L EQU 13
FC_M EQU 14
FC_N EQU 15
FC_O EQU 16
FC_P EQU 17
FC_Q EQU 18
FC_R EQU 19
FC_S EQU 20
FC_T EQU 21
FC_U EQU 22
FC_V EQU 23
FC_W EQU 24
FC_X EQU 25
FC_Y EQU 26
FC_Z EQU 27
FC_0 EQU 28
FC_1 EQU 29
FC_2 EQU 30
FC_3 EQU 31
FC_4 EQU 32
FC_5 EQU 33
FC_6 EQU 34
FC_7 EQU 35
FC_8 EQU 36
FC_9 EQU 37
FC_COL EQU 38
FC_EQ EQU 39
FC_EX EQU 40
FC_DASH EQU 41

BLINK_FLAG EQU 0x40

EE_HISCORE_LO EQU 0x00
EE_HISCORE_HI EQU 0x01
EE_SENTINEL EQU 0x02
EE_VALID EQU 0xA5

; MACROS
MOVLF MACRO LIT, DEST
        MOVLW LIT
        MOVWF DEST
        ENDM

MOVFFREG MACRO SRC, DEST
        MOVF SRC, W
        MOVWF DEST
        ENDM

CLR16 MACRO LO, HI
        CLRF LO
        CLRF HI
        ENDM

CMP_LIT MACRO REG, LIT
        MOVLW LIT
        SUBWF REG, W
        ENDM

GLCD_CS1_ON MACRO
        BSF PORTB, GLCD_CS1_B
        BCF PORTB, GLCD_CS2_B
        ENDM

GLCD_CS2_ON MACRO
        BCF PORTB, GLCD_CS1_B
        BSF PORTB, GLCD_CS2_B
        ENDM

GLCD_CS_NONE MACRO
        BCF PORTB, GLCD_CS1_B
        BCF PORTB, GLCD_CS2_B
        ENDM

GLCD_CMD_MODE MACRO
        BCF PORTB, GLCD_DI_B
        ENDM

GLCD_DATA_MODE MACRO
        BSF PORTB, GLCD_DI_B
        ENDM

GLCD_WRITE_MODE MACRO
        BCF PORTB, GLCD_RW_B
        ENDM

GLCD_EN_PULSE MACRO
        BSF PORTB, GLCD_EN_B
        NOP
        NOP
        NOP
        BCF PORTB, GLCD_EN_B
        NOP
        ENDM

GLCD_RST_LOW MACRO
        BCF PORTB, GLCD_RST_B
        ENDM

GLCD_RST_HIGH MACRO
        BSF PORTB, GLCD_RST_B
        ENDM

; VECTORS
PSECT resetVec, class=CODE, delta=2, abs, ovrld
    ORG 0x0000
    GOTO SYSTEM_INIT

PSECT isrVec, class=CODE, delta=2, abs, ovrld
    ORG 0x0004
    GOTO ISR_HANDLER

; MAIN CODE
PSECT mainCode, class=CODE, delta=2

ISR_HANDLER:
    MOVWF W_TEMP
    SWAPF STATUS, W
    MOVWF STATUS_TEMP
    BCF STATUS, 5
    BCF STATUS, 6
    MOVF PCLATH, W
    MOVWF PCLATH_TEMP
    CLRF PCLATH
    BTFSC INTCON, 2
    CALL TIMER0_ISR
    MOVF PCLATH_TEMP, W
    MOVWF PCLATH
    SWAPF STATUS_TEMP, W
    MOVWF STATUS
    SWAPF W_TEMP, F
    SWAPF W_TEMP, W
    RETFIE

TIMER0_ISR:
    MOVLF TMR0_RELOAD, TMR0
    INCF TICK_COUNTER, F
    BSF ISR_FLAGS, FLAG_TICK
    BCF INTCON, 2
    RETURN

; LOAD_SPRITES
LOAD_SPRITES:
    MOVLF 0x00, CAR_TOP_0
    MOVLF 0x3C, CAR_TOP_1
    MOVLF 0x7E, CAR_TOP_2
    MOVLF 0x7E, CAR_TOP_3
    MOVLF 0x7E, CAR_TOP_4
    MOVLF 0x7E, CAR_TOP_5
    MOVLF 0x7E, CAR_TOP_6
    MOVLF 0x7E, CAR_TOP_7
    MOVLF 0x7E, CAR_TOP_8
    MOVLF 0x7E, CAR_TOP_9
    MOVLF 0x3C, CAR_TOP_A
    MOVLF 0x00, CAR_TOP_B
    BANKSEL CAR_BOT_0
    MOVLF 0x3C, CAR_BOT_0
    MOVLF 0x7E, CAR_BOT_1
    MOVLF 0x3C, CAR_BOT_2
    MOVLF 0xFF, CAR_BOT_3
    MOVLF 0xFF, CAR_BOT_4
    MOVLF 0xFF, CAR_BOT_5
    MOVLF 0xFF, CAR_BOT_6
    MOVLF 0xFF, CAR_BOT_7
    MOVLF 0xFF, CAR_BOT_8
    MOVLF 0x3C, CAR_BOT_9
    MOVLF 0x7E, CAR_BOT_A
    MOVLF 0x3C, CAR_BOT_B
    RETURN

; EEPROM READ
EEPROM_READ:
    BANKSEL EEADR
    MOVWF EEADR
    BANKSEL EECON1
    BCF EECON1, 7
    BSF EECON1, 0
    BANKSEL EEDATA
    MOVF EEDATA, W
    BANKSEL GAME_STATE
    RETURN

; EEPROM_WRITE_BYTE
EEPROM_WRITE_BYTE:
    BANKSEL TEMP2
    MOVF TEMP2, W
    BANKSEL EEADR
    MOVWF EEADR
    BANKSEL TEMP1
    MOVF TEMP1, W
    BANKSEL EEDATA
    MOVWF EEDATA
    BANKSEL EECON1
    BCF EECON1, 7
    BSF EECON1, 2
    BCF INTCON, 7
    MOVLW 0x55
    MOVWF EECON2
    MOVLW 0xAA
    MOVWF EECON2
    BSF EECON1, 1
    BSF INTCON, 7
EWB_WAIT:
    BTFSC EECON1, 1
    GOTO EWB_WAIT
    BCF EECON1, 2
    BANKSEL GAME_STATE
    RETURN

; EEPROM_LOAD_HISCORE
EEPROM_LOAD_HISCORE:
    MOVLW EE_SENTINEL
    CALL EEPROM_READ
    MOVWF TEMP1
    MOVLW EE_VALID
    SUBWF TEMP1, W
    BTFSS STATUS, 2
    GOTO ELH_INVALID

    MOVLW EE_HISCORE_LO
    CALL EEPROM_READ
    BANKSEL HISCORE_LO
    MOVWF HISCORE_LO

    MOVLW EE_HISCORE_HI
    CALL EEPROM_READ
    BANKSEL HISCORE_HI
    MOVWF HISCORE_HI
    RETURN

ELH_INVALID:
    BANKSEL HISCORE_LO
    CLRF HISCORE_LO
    CLRF HISCORE_HI
    RETURN

; EEPROM_SAVE_HISCORE
EEPROM_SAVE_HISCORE:
    BANKSEL HISCORE_LO
    MOVFFREG HISCORE_LO, TEMP1
    MOVLF EE_HISCORE_LO, TEMP2
    CALL EEPROM_WRITE_BYTE

    BANKSEL HISCORE_HI
    MOVFFREG HISCORE_HI, TEMP1
    MOVLF EE_HISCORE_HI, TEMP2
    CALL EEPROM_WRITE_BYTE

    MOVLF EE_VALID, TEMP1
    MOVLF EE_SENTINEL, TEMP2
    CALL EEPROM_WRITE_BYTE
    RETURN

; CHECK_AND_SAVE_HISCORE
CHECK_AND_SAVE_HISCORE:
    BANKSEL NEW_BEST
    CLRF NEW_BEST

    BANKSEL SCORE_HI
    MOVF SCORE_HI, W
    BANKSEL HISCORE_HI
    SUBWF HISCORE_HI, W
    BTFSS STATUS, 0
    GOTO CASH_NEW_BEST
    BTFSS STATUS, 2
    RETURN

    BANKSEL SCORE_LO
    MOVF SCORE_LO, W
    BANKSEL HISCORE_LO
    SUBWF HISCORE_LO, W
    BTFSS STATUS, 0
    GOTO CASH_NEW_BEST
    RETURN

CASH_NEW_BEST:
    BANKSEL SCORE_LO
    MOVFFREG SCORE_LO, HISCORE_LO
    MOVFFREG SCORE_HI, HISCORE_HI
    MOVLF 1, NEW_BEST
    RETURN

; SYSTEM_INIT
SYSTEM_INIT:
    BANKSEL GAME_STATE
    MOVLW 0x20
    MOVWF FSR
CLR_LOOP:
    CLRF INDF
    INCF FSR, F
    MOVLW 0x6C
    SUBWF FSR, W
    BTFSS STATUS, 2
    GOTO CLR_LOOP

    CALL GPIO_INIT
    CALL TIMER0_INIT
    BSF INTCON, 7

    CALL LOAD_SPRITES
    CALL EEPROM_LOAD_HISCORE
    CALL GLCD_INIT

    BANKSEL GAME_STATE
    MOVLF STATE_MENU, GAME_STATE

    CALL DRAW_BOOT_SPLASH
    CALL DRAW_MENU
    GOTO MAIN_LOOP

; GAME_RESET
GAME_RESET:
    BANKSEL GAME_STATE
    MOVLF STATE_PLAY, GAME_STATE
    MOVLF FUEL_MAX, FUEL_LEVEL
    MOVLF FUEL_MAX, PREV_FUEL
    MOVLF FUEL_DEC_INT,FUEL_TICK
    MOVLF SPEED_LVL1, SPEED_LEVEL
    MOVLF 1, LEVEL
    MOVLF 1, PLAYER_LANE
    MOVLF 1, PREV_LANE
    CLR16 SCORE_LO, SCORE_HI
    CLRF ROAD_SCROLL
    CLRF GAME_TICK
    CLRF ACTIVE_ENEMIES
    MOVLF SPAWN_LVL1, SPAWN_TIMER
    MOVLF ENEMY_INACTIVE, EN0_LANE
    MOVLF ENEMY_INACTIVE, EN1_LANE
    MOVLF ENEMY_INACTIVE, EN2_LANE
    MOVLF ENEMY_INACTIVE, FUEL_LANE
    CLRF EN0_ROW
    CLRF EN1_ROW
    CLRF EN2_ROW
    MOVLF 0x01, HUD_DIRTY
    CLRF NEW_BEST
    CLRF BLINK_FLAG
    MOVLF 0xAC, LFSR_HI
    MOVLF 0xE1, LFSR_LO

    CALL GLCD_CLEAR_ALL
    CALL DRAW_HUD
    CALL DRAW_ROAD
    CALL DRAW_CAR

    BANKSEL PORTC
    BSF PORTC, 2
    RETURN

; TIMER0_INIT
TIMER0_INIT:
    BANKSEL OPTION_REG
    MOVLW 0b11000111
    MOVWF OPTION_REG
    BANKSEL TMR0
    CLRF TMR0
    MOVLF TMR0_RELOAD, TMR0
    BANKSEL TICK_COUNTER
    CLRF TICK_COUNTER
    CLRF GAME_TICK
    CLRF ISR_FLAGS
    BSF INTCON, 5
    RETURN

; GPIO_INIT
GPIO_INIT:
    BANKSEL ADCON1
    MOVLW 0x06
    MOVWF ADCON1
    BANKSEL TRISA
    MOVLW 0b00000111
    MOVWF TRISA
    BANKSEL TRISB
    MOVLW 0b00000000
    MOVWF TRISB
    BANKSEL TRISC
    MOVLW 0b11111011
    MOVWF TRISC
    BANKSEL TRISD
    MOVLW 0b00000000
    MOVWF TRISD
    BANKSEL PORTA
    CLRF PORTA
    CLRF PORTB
    CLRF PORTC
    CLRF PORTD
    BSF PORTB, GLCD_RST_B
    BANKSEL BTN_STATE
    MOVLF 0x07, BTN_PREV
    MOVLF 0x07, BTN_STATE
    CLRF BTN_EVENT
    RETURN

; BUTTON_SCAN
BUTTON_SCAN:
    BANKSEL PORTA
    MOVF PORTA, W
    ANDLW BTN_MASK_C
    XORLW BTN_MASK_C
    BANKSEL TEMP1
    MOVWF TEMP1
    MOVF BTN_PREV, W
    XORWF TEMP1, W
    MOVWF TEMP2
    MOVF TEMP1, W
    ANDWF TEMP2, W
    MOVWF BTN_EVENT
    MOVFFREG TEMP1, BTN_STATE
    MOVFFREG TEMP1, BTN_PREV
    RETURN

; GLCD DRIVER
GLCD_INIT:
    GLCD_RST_LOW
    MOVLW 1
    CALL DELAY_TICKS
    GLCD_RST_HIGH
    MOVLW 1
    CALL DELAY_TICKS
    GLCD_CS1_ON
    MOVLW GLCD_ON
    CALL GLCD_WRITE_CMD
    MOVLW GLCD_STARTLINE
    CALL GLCD_WRITE_CMD
    MOVLW GLCD_SET_PAGE
    CALL GLCD_WRITE_CMD
    MOVLW GLCD_SET_Y
    CALL GLCD_WRITE_CMD
    GLCD_CS2_ON
    MOVLW GLCD_ON
    CALL GLCD_WRITE_CMD
    MOVLW GLCD_STARTLINE
    CALL GLCD_WRITE_CMD
    MOVLW GLCD_SET_PAGE
    CALL GLCD_WRITE_CMD
    MOVLW GLCD_SET_Y
    CALL GLCD_WRITE_CMD
    CALL GLCD_CLEAR_ALL
    GLCD_CS_NONE
    RETURN

GLCD_WRITE_CMD:
    BANKSEL DISP_TEMP
    MOVWF DISP_TEMP
    GLCD_CMD_MODE
    GLCD_WRITE_MODE
    BANKSEL PORTD
    MOVF DISP_TEMP, W
    MOVWF PORTD
    GLCD_EN_PULSE
    RETURN

GLCD_WRITE_DATA:
    BANKSEL DISP_TEMP
    MOVWF DISP_TEMP
    GLCD_DATA_MODE
    GLCD_WRITE_MODE
    BANKSEL PORTD
    MOVF DISP_TEMP, W
    MOVWF PORTD
    GLCD_EN_PULSE
    RETURN

GLCD_CLEAR_HALF:
    BANKSEL DISP_PAGE
    CLRF DISP_PAGE
CLRH_PAGE:
    BANKSEL DISP_PAGE
    MOVF DISP_PAGE, W
    IORLW GLCD_SET_PAGE
    CALL GLCD_WRITE_CMD
    MOVLW GLCD_SET_Y
    CALL GLCD_WRITE_CMD
    BANKSEL DISP_COL
    CLRF DISP_COL
CLRH_COL:
    MOVLW 0x00
    CALL GLCD_WRITE_DATA
    BANKSEL DISP_COL
    INCF DISP_COL, F
    MOVLW 64
    SUBWF DISP_COL, W
    BTFSS STATUS, 2
    GOTO CLRH_COL
    BANKSEL DISP_PAGE
    INCF DISP_PAGE, F
    MOVLW 8
    SUBWF DISP_PAGE, W
    BTFSS STATUS, 2
    GOTO CLRH_PAGE
    RETURN

GLCD_CLEAR_ALL:
    GLCD_CS1_ON
    CALL GLCD_CLEAR_HALF
    GLCD_CS2_ON
    CALL GLCD_CLEAR_HALF
    GLCD_CS_NONE
    RETURN

GLCD_PUT_BYTE:
    BANKSEL DRAW_X
    MOVLW 64
    SUBWF DRAW_X, W
    BTFSS STATUS, 0
    GOTO GPB_CS1
    GLCD_CS2_ON
    BANKSEL DRAW_X
    MOVLW 64
    SUBWF DRAW_X, W
    GOTO GPB_COL
GPB_CS1:
    GLCD_CS1_ON
    BANKSEL DRAW_X
    MOVF DRAW_X, W
GPB_COL:
    IORLW GLCD_SET_Y
    CALL GLCD_WRITE_CMD
    BANKSEL DRAW_PAGE
    MOVF DRAW_PAGE, W
    IORLW GLCD_SET_PAGE
    CALL GLCD_WRITE_CMD
    BANKSEL DISP_BYTE
    MOVF DISP_BYTE, W
    CALL GLCD_WRITE_DATA
    GLCD_CS_NONE
    RETURN

DRAW_SOLID_ROW:
    BANKSEL DRAW_X
    CLRF DRAW_X
DSR2_LOOP:
    BANKSEL DISP_BYTE
    MOVLF 0xFF, DISP_BYTE
    CALL GLCD_PUT_BYTE
    BANKSEL DRAW_X
    INCF DRAW_X, F
    MOVLW 128
    SUBWF DRAW_X, W
    BTFSS STATUS, 2
    GOTO DSR2_LOOP
    RETURN

DRAW_CLEAR_ROW:
    BANKSEL DRAW_X
    CLRF DRAW_X
DCR_LOOP:
    BANKSEL DISP_BYTE
    MOVLF 0x00, DISP_BYTE
    CALL GLCD_PUT_BYTE
    BANKSEL DRAW_X
    INCF DRAW_X, F
    MOVLW 128
    SUBWF DRAW_X, W
    BTFSS STATUS, 2
    GOTO DCR_LOOP
    RETURN

; DELAY_TICKS
DELAY_TICKS:
    BANKSEL TEMP1
    MOVWF TEMP1
    BANKSEL TICK_COUNTER
    MOVF TICK_COUNTER, W
    BANKSEL TEMP1
    ADDWF TEMP1, F
DLY_WAIT:
    BANKSEL TICK_COUNTER
    MOVF TICK_COUNTER, W
    BANKSEL TEMP1
    SUBWF TEMP1, W
    BTFSS STATUS, 2
    GOTO DLY_WAIT
    BCF ISR_FLAGS, FLAG_TICK
    RETURN

; GET_FONT_BYTE
GET_FONT_BYTE:
    MOVWF TEMP3
    MOVLW HIGH(FONT_TABLE)
    MOVWF PCLATH
    MOVF TEMP3, W
    CALL FONT_TABLE
    CLRF PCLATH
    RETURN

; DRAW_CHAR
DRAW_CHAR:
    MOVF TEMP1, W
    MOVWF TEMP2
    BCF STATUS, 0
    RLF TEMP2, F
    BCF STATUS, 0
    RLF TEMP2, F
    MOVF TEMP1, W
    ADDWF TEMP2, F
    MOVLF 5, LOOP_CNT
DCH_LOOP:
    MOVF TEMP2, W
    CALL GET_FONT_BYTE
    MOVWF DISP_BYTE
    CALL GLCD_PUT_BYTE
    INCF DRAW_X, F
    INCF TEMP2, F
    DECF LOOP_CNT, F
    BTFSS STATUS, 2
    GOTO DCH_LOOP
    MOVLF 0x00, DISP_BYTE
    CALL GLCD_PUT_BYTE
    INCF DRAW_X, F
    RETURN

; SCORE_TO_BCD_3
SCORE_TO_BCD_3:
    CLRF TEMP1
    CLRF TEMP2
    BANKSEL SCORE_LO
    MOVF SCORE_LO, W
    BANKSEL TEMP3
    MOVWF TEMP3
S3H:
    MOVLW 100
    SUBWF TEMP3, W
    BTFSS STATUS, 0
    GOTO S3T
    MOVWF TEMP3
    INCF TEMP1, F
    GOTO S3H
S3T:
    MOVLW 10
    SUBWF TEMP3, W
    BTFSS STATUS, 0
    GOTO S3DONE
    MOVWF TEMP3
    INCF TEMP2, F
    GOTO S3T
S3DONE:
    RETURN

HISCORE_TO_BCD_3:
    CLRF TEMP1
    CLRF TEMP2
    BANKSEL HISCORE_LO
    MOVF HISCORE_LO, W
    BANKSEL TEMP3
    MOVWF TEMP3
    GOTO S3H

DRAW_3DIGITS:
    BANKSEL SCORE_DISP
    MOVF TEMP2, W
    MOVWF SCORE_DISP
    MOVF TEMP3, W
    MOVWF PREV_FUEL
    MOVF TEMP1, W
    ADDLW FC_0
    MOVWF TEMP1
    CALL DRAW_CHAR
    BANKSEL SCORE_DISP
    MOVF SCORE_DISP, W
    ADDLW FC_0
    MOVWF TEMP1
    CALL DRAW_CHAR
    BANKSEL PREV_FUEL
    MOVF PREV_FUEL, W
    ADDLW FC_0
    MOVWF TEMP1
    CALL DRAW_CHAR
    RETURN

; DRAW_PRESS_SELECT
DRAW_PRESS_SELECT:
    MOVLF 7, DRAW_PAGE
    MOVLF 28, DRAW_X
    MOVLF FC_P, TEMP1
    CALL DRAW_CHAR
    MOVLF FC_R, TEMP1
    CALL DRAW_CHAR
    MOVLF FC_E, TEMP1
    CALL DRAW_CHAR
    MOVLF FC_S, TEMP1
    CALL DRAW_CHAR
    MOVLF FC_S, TEMP1
    CALL DRAW_CHAR
    MOVLF FC_SPC, TEMP1
    CALL DRAW_CHAR
    MOVLF FC_S, TEMP1
    CALL DRAW_CHAR
    MOVLF FC_E, TEMP1
    CALL DRAW_CHAR
    MOVLF FC_L, TEMP1
    CALL DRAW_CHAR
    MOVLF FC_E, TEMP1
    CALL DRAW_CHAR
    MOVLF FC_C, TEMP1
    CALL DRAW_CHAR
    MOVLF FC_T, TEMP1
    CALL DRAW_CHAR
    RETURN

; DRAW_MENU_CURSOR
DRAW_MENU_CURSOR:
    MOVLF 6, DRAW_PAGE
    MOVLF 46, DRAW_X
    MOVLF FC_GT, TEMP1
    CALL DRAW_CHAR
    RETURN

; DRAW_HI_HEADER
DRAW_HI_HEADER:
    CLRF DRAW_PAGE
    CLRF DRAW_X
    MOVLF FC_H, TEMP1
    CALL DRAW_CHAR
    MOVLF FC_I, TEMP1
    CALL DRAW_CHAR
    MOVLF FC_COL, TEMP1
    CALL DRAW_CHAR
    CALL HISCORE_TO_BCD_3
    CALL DRAW_3DIGITS

    MOVLF 1, DRAW_PAGE
    CLRF DRAW_X
DHH_DIV_LOOP:
    MOVLF 0x08, DISP_BYTE
    CALL GLCD_PUT_BYTE
    INCF DRAW_X, F
    MOVLW 128
    SUBWF DRAW_X, W
    BTFSS STATUS, 2
    GOTO DHH_DIV_LOOP
    RETURN

; DRAW_NEW_RECORD
DRAW_NEW_RECORD:
    MOVLF 4, DRAW_PAGE
    MOVLF 31, DRAW_X
    MOVLF FC_N, TEMP1
    CALL DRAW_CHAR
    MOVLF FC_E, TEMP1
    CALL DRAW_CHAR
    MOVLF FC_W, TEMP1
    CALL DRAW_CHAR
    MOVLF FC_SPC, TEMP1
    CALL DRAW_CHAR
    MOVLF FC_R, TEMP1
    CALL DRAW_CHAR
    MOVLF FC_E, TEMP1
    CALL DRAW_CHAR
    MOVLF FC_C, TEMP1
    CALL DRAW_CHAR
    MOVLF FC_O, TEMP1
    CALL DRAW_CHAR
    MOVLF FC_R, TEMP1
    CALL DRAW_CHAR
    MOVLF FC_D, TEMP1
    CALL DRAW_CHAR
    MOVLF FC_EX, TEMP1
    CALL DRAW_CHAR
    RETURN

; DRAW_BOOT_SPLASH
DRAW_BOOT_SPLASH:
    MOVLF 2, DRAW_PAGE
    MOVLF 34, DRAW_X
    MOVLF FC_R, TEMP1
    CALL DRAW_CHAR
    MOVLF FC_A, TEMP1
    CALL DRAW_CHAR
    MOVLF FC_C, TEMP1
    CALL DRAW_CHAR
    MOVLF FC_I, TEMP1
    CALL DRAW_CHAR
    MOVLF FC_N, TEMP1
    CALL DRAW_CHAR
    MOVLF FC_G, TEMP1
    CALL DRAW_CHAR
    MOVLF FC_SPC, TEMP1
    CALL DRAW_CHAR
    MOVLF FC_C, TEMP1
    CALL DRAW_CHAR
    MOVLF FC_A, TEMP1
    CALL DRAW_CHAR
    MOVLF FC_R, TEMP1
    CALL DRAW_CHAR

    MOVLF 4, DRAW_PAGE
    MOVLF 40, DRAW_X
    MOVLF FC_B, TEMP1
    CALL DRAW_CHAR
    MOVLF FC_Y, TEMP1
    CALL DRAW_CHAR
    MOVLF FC_SPC, TEMP1
    CALL DRAW_CHAR
    MOVLF FC_A, TEMP1
    CALL DRAW_CHAR
    MOVLF FC_Y, TEMP1
    CALL DRAW_CHAR
    MOVLF FC_U, TEMP1
    CALL DRAW_CHAR
    MOVLF FC_S, TEMP1
    CALL DRAW_CHAR
    MOVLF FC_H, TEMP1
    CALL DRAW_CHAR

    MOVLF 5, DRAW_PAGE
    MOVLF 49, DRAW_X
    MOVLF FC_Y, TEMP1
    CALL DRAW_CHAR
    MOVLF FC_A, TEMP1
    CALL DRAW_CHAR
    MOVLF FC_J, TEMP1
    CALL DRAW_CHAR
    MOVLF FC_A, TEMP1
    CALL DRAW_CHAR
    MOVLF FC_T, TEMP1
    CALL DRAW_CHAR

    MOVLW 78
    CALL DELAY_TICKS
    RETURN

; DRAW_MENU
DRAW_MENU:
    CALL GLCD_CLEAR_ALL

    CALL DRAW_HI_HEADER

    MOVLF 2, DRAW_PAGE
    MOVLF 34, DRAW_X
    MOVLF FC_R, TEMP1
    CALL DRAW_CHAR
    MOVLF FC_A, TEMP1
    CALL DRAW_CHAR
    MOVLF FC_C, TEMP1
    CALL DRAW_CHAR
    MOVLF FC_I, TEMP1
    CALL DRAW_CHAR
    MOVLF FC_N, TEMP1
    CALL DRAW_CHAR
    MOVLF FC_G, TEMP1
    CALL DRAW_CHAR
    MOVLF FC_SPC, TEMP1
    CALL DRAW_CHAR
    MOVLF FC_C, TEMP1
    CALL DRAW_CHAR
    MOVLF FC_A, TEMP1
    CALL DRAW_CHAR
    MOVLF FC_R, TEMP1
    CALL DRAW_CHAR

    MOVLF 3, DRAW_PAGE
    MOVLF 58, DRAW_X
    MOVLW CAR_TOP_0
    MOVWF FSR
    CALL DRAW_SPRITE_ROW
    MOVLF 4, DRAW_PAGE
    MOVLF 58, DRAW_X
    MOVLW CAR_BOT_0
    MOVWF FSR
    CALL DRAW_SPRITE_ROW

    CALL DRAW_MENU_CURSOR
    MOVLF 6, DRAW_PAGE
    MOVLF 58, DRAW_X
    MOVLF FC_P, TEMP1
    CALL DRAW_CHAR
    MOVLF FC_L, TEMP1
    CALL DRAW_CHAR
    MOVLF FC_A, TEMP1
    CALL DRAW_CHAR
    MOVLF FC_Y, TEMP1
    CALL DRAW_CHAR

    CALL DRAW_PRESS_SELECT
    RETURN

; DRAW_GAMEOVER_SCREEN
DRAW_GAMEOVER_SCREEN:
    CALL GLCD_CLEAR_ALL
    CALL DRAW_HI_HEADER

    MOVLF 2, DRAW_PAGE
    MOVLF 37, DRAW_X
    MOVLF FC_G, TEMP1
    CALL DRAW_CHAR
    MOVLF FC_A, TEMP1
    CALL DRAW_CHAR
    MOVLF FC_M, TEMP1
    CALL DRAW_CHAR
    MOVLF FC_E, TEMP1
    CALL DRAW_CHAR
    MOVLF FC_SPC, TEMP1
    CALL DRAW_CHAR
    MOVLF FC_O, TEMP1
    CALL DRAW_CHAR
    MOVLF FC_V, TEMP1
    CALL DRAW_CHAR
    MOVLF FC_E, TEMP1
    CALL DRAW_CHAR
    MOVLF FC_R, TEMP1
    CALL DRAW_CHAR

    MOVLF 3, DRAW_PAGE
    MOVLF 43, DRAW_X
    MOVLF FC_S, TEMP1
    CALL DRAW_CHAR
    MOVLF FC_C, TEMP1
    CALL DRAW_CHAR
    MOVLF FC_COL, TEMP1
    CALL DRAW_CHAR
    CALL SCORE_TO_BCD_3
    CALL DRAW_3DIGITS

    BANKSEL NEW_BEST
    MOVF NEW_BEST, F
    BTFSC STATUS, 2
    GOTO DGO_SKIP_NR
    CALL DRAW_NEW_RECORD
DGO_SKIP_NR:

    MOVLF 5, DRAW_PAGE
    MOVLF 37, DRAW_X
    MOVLF FC_B, TEMP1
    CALL DRAW_CHAR
    MOVLF FC_E, TEMP1
    CALL DRAW_CHAR
    MOVLF FC_S, TEMP1
    CALL DRAW_CHAR
    MOVLF FC_T, TEMP1
    CALL DRAW_CHAR
    MOVLF FC_COL, TEMP1
    CALL DRAW_CHAR
    CALL HISCORE_TO_BCD_3
    CALL DRAW_3DIGITS

    CALL DRAW_PRESS_SELECT
    RETURN

DRAW_HUD:
    BANKSEL DRAW_PAGE
    MOVLF HUD_PAGE, DRAW_PAGE

    BANKSEL FUEL_LEVEL
    MOVF FUEL_LEVEL, W
    MOVWF TEMP1
    CLRF TEMP2
DIV3_LOOP:
    MOVLW 3
    SUBWF TEMP1, W
    BTFSS STATUS, 0
    GOTO DIV3_DONE
    MOVWF TEMP1
    BANKSEL TEMP2
    INCF TEMP2, F
    GOTO DIV3_LOOP
DIV3_DONE:
    BANKSEL DRAW_X
    CLRF DRAW_X
    BANKSEL TEMP2
    MOVF TEMP2, W
    MOVWF LOOP_CNT
HDF_FILL:
    BANKSEL LOOP_CNT
    MOVF LOOP_CNT, F
    BTFSC STATUS, 2
    GOTO HDF_EMPTY
    BANKSEL DISP_BYTE
    MOVLF 0x7E, DISP_BYTE
    CALL GLCD_PUT_BYTE
    BANKSEL DRAW_X
    INCF DRAW_X, F
    BANKSEL LOOP_CNT
    DECF LOOP_CNT, F
    GOTO HDF_FILL
HDF_EMPTY:
    BANKSEL DRAW_X
    MOVLW 40
    SUBWF DRAW_X, W
    BTFSC STATUS, 0
    GOTO HDF_SEP
    BANKSEL DISP_BYTE
    MOVLF 0x42, DISP_BYTE
    CALL GLCD_PUT_BYTE
    BANKSEL DRAW_X
    INCF DRAW_X, F
    GOTO HDF_EMPTY
HDF_SEP:
    BANKSEL DRAW_X
    MOVLF 40, DRAW_X
    BANKSEL DISP_BYTE
    MOVLF 0xFF, DISP_BYTE
    CALL GLCD_PUT_BYTE

    BANKSEL DRAW_X
    MOVLF 50, DRAW_X
    BANKSEL LEVEL
    MOVF LEVEL, W
    MOVWF LOOP_CNT
HDL_LOOP:
    BANKSEL LOOP_CNT
    MOVF LOOP_CNT, F
    BTFSC STATUS, 2
    GOTO HDS_SCORE
    BANKSEL DISP_BYTE
    MOVLF 0x7E, DISP_BYTE
    CALL GLCD_PUT_BYTE
    BANKSEL DRAW_X
    INCF DRAW_X, F
    BANKSEL LOOP_CNT
    DECF LOOP_CNT, F
    GOTO HDL_LOOP

HDS_SCORE:
    MOVLF 86, DRAW_X
    MOVLF FC_S, TEMP1
    CALL DRAW_CHAR
    MOVLF FC_C, TEMP1
    CALL DRAW_CHAR
    MOVLF FC_COL, TEMP1
    CALL DRAW_CHAR
    CALL SCORE_TO_BCD_3
    CALL DRAW_3DIGITS

    BANKSEL HUD_DIRTY
    CLRF HUD_DIRTY
    RETURN

; DRAW_ROAD
DRAW_ROAD:
    BANKSEL DRAW_PAGE
    MOVLF ROAD_START_PAGE, DRAW_PAGE
DR_PAGE_LOOP:
    BANKSEL DRAW_PAGE
    MOVF DRAW_PAGE, W
    BANKSEL ROAD_SCROLL
    ADDWF ROAD_SCROLL, W
    ANDLW 0x01
    BTFSC STATUS, 2
    GOTO DR_GAP
    BANKSEL DISP_BYTE
    MOVLF 0xFF, DISP_BYTE
    GOTO DR_DIVS
DR_GAP:
    BANKSEL DISP_BYTE
    MOVLF 0x00, DISP_BYTE
DR_DIVS:
    BANKSEL DRAW_X
    MOVLF DIV1_COL, DRAW_X
    CALL GLCD_PUT_BYTE
    BANKSEL DRAW_X
    MOVLF DIV2_COL, DRAW_X
    CALL GLCD_PUT_BYTE
    BANKSEL DRAW_PAGE
    MOVLW 7
    SUBWF DRAW_PAGE, W
    BTFSS STATUS, 2
    GOTO DR_NEXT
    BANKSEL DRAW_X
    CLRF DRAW_X
DR_BORDER:
    BANKSEL DISP_BYTE
    MOVLF 0xFF, DISP_BYTE
    CALL GLCD_PUT_BYTE
    BANKSEL DRAW_X
    INCF DRAW_X, F
    MOVLW 128
    SUBWF DRAW_X, W
    BTFSS STATUS, 2
    GOTO DR_BORDER
DR_NEXT:
    BANKSEL DRAW_PAGE
    INCF DRAW_PAGE, F
    MOVLW 8
    SUBWF DRAW_PAGE, W
    BTFSS STATUS, 2
    GOTO DR_PAGE_LOOP
    RETURN

; LANE X HELPERS
GET_LANE_X:
    BANKSEL PLAYER_LANE
    MOVF PLAYER_LANE, W
    ANDLW 0xFF
    BTFSC STATUS, 2
    GOTO GLX_0
    MOVLW 1
    BANKSEL PLAYER_LANE
    SUBWF PLAYER_LANE, W
    BTFSC STATUS, 2
    GOTO GLX_1
    MOVLF LANE2_X + CAR_OFF, CAR_X
    RETURN
GLX_0:
    MOVLF LANE0_X + CAR_OFF, CAR_X
    RETURN
GLX_1:
    MOVLF LANE1_X + CAR_OFF, CAR_X
    RETURN

GET_PREV_LANE_X:
    BANKSEL PREV_LANE
    MOVF PREV_LANE, W
    ANDLW 0xFF
    BTFSC STATUS, 2
    GOTO GPX_0
    MOVLW 1
    BANKSEL PREV_LANE
    SUBWF PREV_LANE, W
    BTFSC STATUS, 2
    GOTO GPX_1
    MOVLF LANE2_X + CAR_OFF, CAR_X
    RETURN
GPX_0:
    MOVLF LANE0_X + CAR_OFF, CAR_X
    RETURN
GPX_1:
    MOVLF LANE1_X + CAR_OFF, CAR_X
    RETURN

GET_ENEMY_X:
    BANKSEL TEMP3
    MOVF TEMP3, W
    ANDLW 0xFF
    BTFSC STATUS, 2
    GOTO GEX_0
    MOVLW 1
    SUBWF TEMP3, W
    BTFSC STATUS, 2
    GOTO GEX_1
    MOVLF LANE2_X + CAR_OFF, CAR_X
    RETURN
GEX_0:
    MOVLF LANE0_X + CAR_OFF, CAR_X
    RETURN
GEX_1:
    MOVLF LANE1_X + CAR_OFF, CAR_X
    RETURN

; SPRITE ROWS
DRAW_SPRITE_ROW:
    BANKSEL SPRITE_IDX
    MOVLF CAR_WIDTH, SPRITE_IDX
DSR_LOOP:
    MOVF INDF, W
    BANKSEL DISP_BYTE
    MOVWF DISP_BYTE
    CALL GLCD_PUT_BYTE
    INCF FSR, F
    BANKSEL DRAW_X
    INCF DRAW_X, F
    BANKSEL SPRITE_IDX
    DECF SPRITE_IDX, F
    BTFSS STATUS, 2
    GOTO DSR_LOOP
    RETURN

ERASE_SPRITE_ROW:
    BANKSEL SPRITE_IDX
    MOVLF CAR_WIDTH, SPRITE_IDX
ESR_LOOP:
    BANKSEL DISP_BYTE
    MOVLF 0x00, DISP_BYTE
    CALL GLCD_PUT_BYTE
    BANKSEL DRAW_X
    INCF DRAW_X, F
    BANKSEL SPRITE_IDX
    DECF SPRITE_IDX, F
    BTFSS STATUS, 2
    GOTO ESR_LOOP
    RETURN

; DRAW/ERASE CAR
DRAW_CAR:
    CALL GET_LANE_X
    BANKSEL DRAW_PAGE
    MOVLF CAR_PAGE_TOP, DRAW_PAGE
    BANKSEL CAR_X
    MOVFFREG CAR_X, DRAW_X
    MOVLW CAR_TOP_0
    MOVWF FSR
    CALL DRAW_SPRITE_ROW
    BANKSEL DRAW_PAGE
    MOVLF CAR_PAGE_BOT, DRAW_PAGE
    BANKSEL CAR_X
    MOVFFREG CAR_X, DRAW_X
    MOVLW CAR_BOT_0
    MOVWF FSR
    CALL DRAW_SPRITE_ROW
    BANKSEL PLAYER_LANE
    MOVFFREG PLAYER_LANE, PREV_LANE
    RETURN

ERASE_CAR:
    CALL GET_PREV_LANE_X
    BANKSEL DRAW_PAGE
    MOVLF CAR_PAGE_TOP, DRAW_PAGE
    BANKSEL CAR_X
    MOVFFREG CAR_X, DRAW_X
    CALL ERASE_SPRITE_ROW
    BANKSEL DRAW_PAGE
    MOVLF CAR_PAGE_BOT, DRAW_PAGE
    BANKSEL CAR_X
    MOVFFREG CAR_X, DRAW_X
    CALL ERASE_SPRITE_ROW
    RETURN

; DRAW/ERASE ENEMY
DRAW_ENEMY:
    CALL GET_ENEMY_X
    BANKSEL CAR_X
    MOVFFREG CAR_X, DRAW_X
    MOVLW CAR_TOP_0
    MOVWF FSR
    CALL DRAW_SPRITE_ROW
    BANKSEL DRAW_PAGE
    INCF DRAW_PAGE, F
    BANKSEL CAR_X
    MOVFFREG CAR_X, DRAW_X
    MOVLW CAR_BOT_0
    MOVWF FSR
    CALL DRAW_SPRITE_ROW
    BANKSEL DRAW_PAGE
    DECF DRAW_PAGE, F
    RETURN

ERASE_ENEMY:
    CALL GET_ENEMY_X
    BANKSEL CAR_X
    MOVFFREG CAR_X, DRAW_X
    CALL ERASE_SPRITE_ROW
    BANKSEL DRAW_PAGE
    INCF DRAW_PAGE, F
    BANKSEL CAR_X
    MOVFFREG CAR_X, DRAW_X
    CALL ERASE_SPRITE_ROW
    BANKSEL DRAW_PAGE
    DECF DRAW_PAGE, F
    RETURN

; DRAW FUEL PICKUP
DRAW_FUEL_PICKUP:
    BANKSEL FUEL_LANE
    MOVFFREG FUEL_LANE, TEMP3
    CALL GET_ENEMY_X
    BANKSEL CAR_X
    MOVFFREG CAR_X, DRAW_X
    BANKSEL DISP_BYTE
    MOVLF 0x3E, DISP_BYTE
    CALL GLCD_PUT_BYTE
    BANKSEL DRAW_X
    INCF DRAW_X, F
    MOVLF 0x41, DISP_BYTE
    CALL GLCD_PUT_BYTE
    BANKSEL DRAW_X
    INCF DRAW_X, F
    MOVLF 0x5D, DISP_BYTE
    CALL GLCD_PUT_BYTE
    BANKSEL DRAW_X
    INCF DRAW_X, F
    MOVLF 0x41, DISP_BYTE
    CALL GLCD_PUT_BYTE
    BANKSEL DRAW_X
    INCF DRAW_X, F
    MOVLF 0x3E, DISP_BYTE
    CALL GLCD_PUT_BYTE
    RETURN

ERASE_FUEL_PICKUP:
    BANKSEL FUEL_LANE
    MOVFFREG FUEL_LANE, TEMP3
    CALL GET_ENEMY_X
    BANKSEL CAR_X
    MOVFFREG CAR_X, DRAW_X
    BANKSEL SPRITE_IDX
    MOVLF 5, SPRITE_IDX
EFUP_LOOP:
    BANKSEL DISP_BYTE
    MOVLF 0x00, DISP_BYTE
    CALL GLCD_PUT_BYTE
    BANKSEL DRAW_X
    INCF DRAW_X, F
    BANKSEL SPRITE_IDX
    DECF SPRITE_IDX, F
    BTFSS STATUS, 2
    GOTO EFUP_LOOP
    RETURN

; LFSR + RANDOM LANE
LFSR_STEP:
    BANKSEL LFSR_LO
    BTFSS LFSR_LO, 0
    GOTO LFSR_NO_FB
    BCF STATUS, 0
    RRF LFSR_HI, F
    RRF LFSR_LO, F
    MOVLW 0xD4
    XORWF LFSR_LO, F
    RETURN
LFSR_NO_FB:
    BCF STATUS, 0
    RRF LFSR_HI, F
    RRF LFSR_LO, F
    RETURN

GET_RANDOM_LANE:
    CALL LFSR_STEP
    BANKSEL LFSR_LO
    MOVF LFSR_LO, W
    ANDLW 0x03
    MOVWF TEMP3
    MOVLW 3
    SUBWF TEMP3, W
    BTFSS STATUS, 2
    RETURN
    BANKSEL TEMP3
    CLRF TEMP3
    RETURN

; SPAWN_ENEMY
SPAWN_ENEMY:
    BANKSEL ACTIVE_ENEMIES
    MOVLW MAX_ENEMIES
    SUBWF ACTIVE_ENEMIES, W
    BTFSC STATUS, 0
    RETURN

    CALL GET_RANDOM_LANE

    BANKSEL FUEL_LANE
    MOVLW ENEMY_INACTIVE
    SUBWF FUEL_LANE, W
    BTFSS STATUS, 2
    GOTO SE_ENEMY
    BANKSEL LFSR_HI
    BTFSS LFSR_HI, 3
    GOTO SE_ENEMY
    CALL GET_RANDOM_LANE
    BANKSEL FUEL_LANE
    MOVFFREG TEMP3, FUEL_LANE
    MOVLF ROAD_START_PAGE, FUEL_ROW
    BANKSEL DRAW_PAGE
    MOVLF ROAD_START_PAGE, DRAW_PAGE
    CALL DRAW_FUEL_PICKUP
    RETURN

SE_ENEMY:
    BANKSEL EN0_LANE
    MOVLW ENEMY_INACTIVE
    SUBWF EN0_LANE, W
    BTFSC STATUS, 2
    GOTO SE_SLOT0
    BANKSEL EN1_LANE
    MOVLW ENEMY_INACTIVE
    SUBWF EN1_LANE, W
    BTFSC STATUS, 2
    GOTO SE_SLOT1
    BANKSEL EN2_LANE
    MOVLW ENEMY_INACTIVE
    SUBWF EN2_LANE, W
    BTFSC STATUS, 2
    GOTO SE_SLOT2
    RETURN

SE_SLOT0:
    BANKSEL EN0_LANE
    MOVFFREG TEMP3, EN0_LANE
    MOVLF ROAD_START_PAGE, EN0_ROW
    GOTO SE_DONE
SE_SLOT1:
    BANKSEL EN1_LANE
    MOVFFREG TEMP3, EN1_LANE
    MOVLF ROAD_START_PAGE, EN1_ROW
    GOTO SE_DONE
SE_SLOT2:
    BANKSEL EN2_LANE
    MOVFFREG TEMP3, EN2_LANE
    MOVLF ROAD_START_PAGE, EN2_ROW

SE_DONE:
    BANKSEL ACTIVE_ENEMIES
    INCF ACTIVE_ENEMIES, F
    BANKSEL DRAW_PAGE
    MOVLF ROAD_START_PAGE, DRAW_PAGE
    CALL DRAW_ENEMY
    RETURN

; INCREMENT_SCORE + LEVEL UP
INCREMENT_SCORE:
    BANKSEL SCORE_LO
    INCF SCORE_LO, F
    BTFSC STATUS, 2
    INCF SCORE_HI, F
    MOVLF 1, HUD_DIRTY

    BANKSEL SCORE_LO
    MOVF SCORE_LO, W
    MOVWF TEMP1

    CMP_LIT TEMP1, SCORE_LVL5
    BTFSC STATUS, 0
    GOTO SET_LVL5
    CMP_LIT TEMP1, SCORE_LVL4
    BTFSC STATUS, 0
    GOTO SET_LVL4
    CMP_LIT TEMP1, SCORE_LVL3
    BTFSC STATUS, 0
    GOTO SET_LVL3
    CMP_LIT TEMP1, SCORE_LVL2
    BTFSC STATUS, 0
    GOTO SET_LVL2
    RETURN

SET_LVL2:
    BANKSEL LEVEL
    CMP_LIT LEVEL, 2
    BTFSC STATUS, 0
    RETURN
    MOVLF 2, LEVEL
    MOVLF SPEED_LVL2, SPEED_LEVEL
    RETURN
SET_LVL3:
    BANKSEL LEVEL
    CMP_LIT LEVEL, 3
    BTFSC STATUS, 0
    RETURN
    MOVLF 3, LEVEL
    MOVLF SPEED_LVL3, SPEED_LEVEL
    RETURN
SET_LVL4:
    BANKSEL LEVEL
    CMP_LIT LEVEL, 4
    BTFSC STATUS, 0
    RETURN
    MOVLF 4, LEVEL
    MOVLF SPEED_LVL4, SPEED_LEVEL
    RETURN
SET_LVL5:
    BANKSEL LEVEL
    CMP_LIT LEVEL, 5
    BTFSC STATUS, 0
    RETURN
    MOVLF 5, LEVEL
    MOVLF SPEED_LVL5, SPEED_LEVEL
    RETURN

; UPDATE_FUEL_PICKUP
UPDATE_FUEL_PICKUP:
    BANKSEL FUEL_LANE
    MOVLW ENEMY_INACTIVE
    SUBWF FUEL_LANE, W
    BTFSC STATUS, 2
    RETURN

    BANKSEL FUEL_ROW
    MOVFFREG FUEL_ROW, DRAW_PAGE
    CALL ERASE_FUEL_PICKUP

    BANKSEL FUEL_ROW
    INCF FUEL_ROW, F

    MOVLW CAR_PAGE_TOP
    SUBWF FUEL_ROW, W
    BTFSS STATUS, 2
    GOTO UFP_CHECK_GONE

    BANKSEL FUEL_LANE
    MOVF FUEL_LANE, W
    BANKSEL PLAYER_LANE
    SUBWF PLAYER_LANE, W
    BTFSS STATUS, 2
    GOTO UFP_CHECK_GONE

    BANKSEL FUEL_LEVEL
    MOVLW 30
    ADDWF FUEL_LEVEL, F
    MOVLW FUEL_MAX
    SUBWF FUEL_LEVEL, W
    BTFSS STATUS, 0
    GOTO UFP_COLLECTED
    MOVLF FUEL_MAX, FUEL_LEVEL
UFP_COLLECTED:
    MOVLF ENEMY_INACTIVE, FUEL_LANE
    MOVLF 1, HUD_DIRTY
    RETURN

UFP_CHECK_GONE:
    BANKSEL FUEL_ROW
    MOVLW 8
    SUBWF FUEL_ROW, W
    BTFSC STATUS, 0
    GOTO UFP_GONE
    BANKSEL FUEL_ROW
    MOVFFREG FUEL_ROW, DRAW_PAGE
    CALL DRAW_FUEL_PICKUP
    RETURN
UFP_GONE:
    MOVLF ENEMY_INACTIVE, FUEL_LANE
    RETURN

; UPDATE_ENEMIES
UPDATE_ENEMIES:
    BANKSEL EN0_LANE
    MOVLW ENEMY_INACTIVE
    SUBWF EN0_LANE, W
    BTFSC STATUS, 2
    GOTO UE_SKIP0
    BANKSEL EN0_ROW
    MOVFFREG EN0_ROW, DRAW_PAGE
    BANKSEL EN0_LANE
    MOVFFREG EN0_LANE, TEMP3
    CALL ERASE_ENEMY
    BANKSEL EN0_ROW
    INCF EN0_ROW, F
    MOVLW CAR_PAGE_TOP
    SUBWF EN0_ROW, W
    BTFSC STATUS, 0
    CALL CHECK_COLLISION
    BANKSEL EN0_ROW
    MOVLW 8
    SUBWF EN0_ROW, W
    BTFSS STATUS, 0
    GOTO UE_DRAW0
    MOVLF ENEMY_INACTIVE, EN0_LANE
    BANKSEL ACTIVE_ENEMIES
    MOVF ACTIVE_ENEMIES, F
    BTFSS STATUS, 2
    DECF ACTIVE_ENEMIES, F
    CALL INCREMENT_SCORE
    GOTO UE_SKIP0
UE_DRAW0:
    BANKSEL EN0_ROW
    MOVFFREG EN0_ROW, DRAW_PAGE
    BANKSEL EN0_LANE
    MOVFFREG EN0_LANE, TEMP3
    CALL DRAW_ENEMY
UE_SKIP0:

    BANKSEL EN1_LANE
    MOVLW ENEMY_INACTIVE
    SUBWF EN1_LANE, W
    BTFSC STATUS, 2
    GOTO UE_SKIP1
    BANKSEL EN1_ROW
    MOVFFREG EN1_ROW, DRAW_PAGE
    BANKSEL EN1_LANE
    MOVFFREG EN1_LANE, TEMP3
    CALL ERASE_ENEMY
    BANKSEL EN1_ROW
    INCF EN1_ROW, F
    MOVLW CAR_PAGE_TOP
    SUBWF EN1_ROW, W
    BTFSC STATUS, 0
    CALL CHECK_COLLISION
    BANKSEL EN1_ROW
    MOVLW 8
    SUBWF EN1_ROW, W
    BTFSS STATUS, 0
    GOTO UE_DRAW1
    MOVLF ENEMY_INACTIVE, EN1_LANE
    BANKSEL ACTIVE_ENEMIES
    MOVF ACTIVE_ENEMIES, F
    BTFSS STATUS, 2
    DECF ACTIVE_ENEMIES, F
    CALL INCREMENT_SCORE
    GOTO UE_SKIP1
UE_DRAW1:
    BANKSEL EN1_ROW
    MOVFFREG EN1_ROW, DRAW_PAGE
    BANKSEL EN1_LANE
    MOVFFREG EN1_LANE, TEMP3
    CALL DRAW_ENEMY
UE_SKIP1:

    BANKSEL EN2_LANE
    MOVLW ENEMY_INACTIVE
    SUBWF EN2_LANE, W
    BTFSC STATUS, 2
    GOTO UE_SKIP2
    BANKSEL EN2_ROW
    MOVFFREG EN2_ROW, DRAW_PAGE
    BANKSEL EN2_LANE
    MOVFFREG EN2_LANE, TEMP3
    CALL ERASE_ENEMY
    BANKSEL EN2_ROW
    INCF EN2_ROW, F
    MOVLW CAR_PAGE_TOP
    SUBWF EN2_ROW, W
    BTFSC STATUS, 0
    CALL CHECK_COLLISION
    BANKSEL EN2_ROW
    MOVLW 8
    SUBWF EN2_ROW, W
    BTFSS STATUS, 0
    GOTO UE_DRAW2
    MOVLF ENEMY_INACTIVE, EN2_LANE
    BANKSEL ACTIVE_ENEMIES
    MOVF ACTIVE_ENEMIES, F
    BTFSS STATUS, 2
    DECF ACTIVE_ENEMIES, F
    CALL INCREMENT_SCORE
    GOTO UE_SKIP2
UE_DRAW2:
    BANKSEL EN2_ROW
    MOVFFREG EN2_ROW, DRAW_PAGE
    BANKSEL EN2_LANE
    MOVFFREG EN2_LANE, TEMP3
    CALL DRAW_ENEMY
UE_SKIP2:
    RETURN

; COLLISION CHECKS
CHECK_COLLISION:
    BANKSEL TEMP3
    MOVF TEMP3, W
    BANKSEL PLAYER_LANE
    SUBWF PLAYER_LANE, W
    BTFSS STATUS, 2
    RETURN
    BANKSEL ISR_FLAGS
    BSF ISR_FLAGS, FLAG_COLLISION
    RETURN

; DO_GAME_OVER
DO_GAME_OVER:
    BANKSEL GAME_STATE
    MOVLF STATE_GAMEOVER, GAME_STATE

    CALL CHECK_AND_SAVE_HISCORE
    CALL DRAW_GAMEOVER_SCREEN
    RETURN

; MAIN_LOOP
MAIN_LOOP:
    BANKSEL ISR_FLAGS
    BTFSS ISR_FLAGS, FLAG_TICK
    GOTO MAIN_LOOP
    BCF ISR_FLAGS, FLAG_TICK

    CALL BUTTON_SCAN

    BANKSEL GAME_STATE
    CMP_LIT GAME_STATE, STATE_PLAY
    BTFSS STATUS, 2
    GOTO ML_FSM

    BANKSEL GAME_TICK
    INCF GAME_TICK, F
    BANKSEL SPEED_LEVEL
    MOVF SPEED_LEVEL, W
    BANKSEL GAME_TICK
    SUBWF GAME_TICK, W
    BTFSS STATUS, 2
    GOTO ML_HUD_CHECK

    BANKSEL GAME_TICK
    CLRF GAME_TICK
    BANKSEL ROAD_SCROLL
    INCF ROAD_SCROLL, F
    MOVLW 8
    SUBWF ROAD_SCROLL, W
    BTFSS STATUS, 2
    GOTO ML_SCROLL
    BANKSEL ROAD_SCROLL
    CLRF ROAD_SCROLL

ML_SCROLL:
    BANKSEL FUEL_TICK
    DECF FUEL_TICK, F
    BTFSS STATUS, 2
    GOTO ML_NO_FUEL
    MOVLF FUEL_DEC_INT, FUEL_TICK
    BANKSEL FUEL_LEVEL
    MOVF FUEL_LEVEL, F
    BTFSC STATUS, 2
    GOTO ML_DO_GAME_OVER
    DECF FUEL_LEVEL, F
    MOVLF 1, HUD_DIRTY
ML_NO_FUEL:

    BANKSEL SPAWN_TIMER
    DECF SPAWN_TIMER, F
    BTFSS STATUS, 2
    GOTO ML_NO_SPAWN
    BANKSEL LEVEL
    MOVF LEVEL, W
    MOVWF TEMP1
    CMP_LIT TEMP1, 5
    BTFSC STATUS, 2
    GOTO ML_SP5
    CMP_LIT TEMP1, 4
    BTFSC STATUS, 2
    GOTO ML_SP4
    CMP_LIT TEMP1, 3
    BTFSC STATUS, 2
    GOTO ML_SP3
    CMP_LIT TEMP1, 2
    BTFSC STATUS, 2
    GOTO ML_SP2
    MOVLF SPAWN_LVL1, SPAWN_TIMER
    GOTO ML_DO_SPAWN
ML_SP2: MOVLF SPAWN_LVL2, SPAWN_TIMER
    GOTO ML_DO_SPAWN
ML_SP3: MOVLF SPAWN_LVL3, SPAWN_TIMER
    GOTO ML_DO_SPAWN
ML_SP4: MOVLF SPAWN_LVL4, SPAWN_TIMER
    GOTO ML_DO_SPAWN
ML_SP5: MOVLF SPAWN_LVL5, SPAWN_TIMER
ML_DO_SPAWN:
    CALL SPAWN_ENEMY
ML_NO_SPAWN:

    CALL UPDATE_FUEL_PICKUP
    CALL UPDATE_ENEMIES
    BANKSEL ISR_FLAGS
    BTFSC ISR_FLAGS, FLAG_COLLISION
    GOTO ML_DO_GAME_OVER
    CALL DRAW_ROAD
    CALL DRAW_CAR
    GOTO ML_HUD_CHECK
ML_DO_GAME_OVER:
    BCF ISR_FLAGS, FLAG_COLLISION
    BANKSEL HUD_DIRTY
    CLRF HUD_DIRTY
    CALL DO_GAME_OVER
    GOTO MAIN_LOOP

ML_HUD_CHECK:
    BANKSEL HUD_DIRTY
    MOVF HUD_DIRTY, F
    BTFSS STATUS, 2
    CALL DRAW_HUD

ML_FSM:
    BANKSEL GAME_STATE
    CMP_LIT GAME_STATE, STATE_PLAY
    BTFSC STATUS, 2
    GOTO FSM_PLAY

    CMP_LIT GAME_STATE, STATE_PAUSE
    BTFSC STATUS, 2
    GOTO FSM_PAUSE

    CMP_LIT GAME_STATE, STATE_GAMEOVER
    BTFSC STATUS, 2
    GOTO FSM_GAMEOVER

    CMP_LIT GAME_STATE, STATE_MENU
    BTFSC STATUS, 2
    GOTO FSM_MENU

    MOVLF STATE_MENU, GAME_STATE
    GOTO MAIN_LOOP

; FSM STATES
FSM_PLAY:
    BANKSEL BTN_EVENT
    BTFSS BTN_EVENT, BTN_SEL_B
    GOTO FP_LEFT
    BANKSEL GAME_STATE
    MOVLF STATE_PAUSE, GAME_STATE
    GOTO MAIN_LOOP
FP_LEFT:
    BANKSEL BTN_EVENT
    BTFSS BTN_EVENT, BTN_LEFT_B
    GOTO FP_RIGHT
    BANKSEL PLAYER_LANE
    MOVF PLAYER_LANE, F
    BTFSC STATUS, 2
    GOTO MAIN_LOOP
    CALL ERASE_CAR
    BANKSEL PLAYER_LANE
    DECF PLAYER_LANE, F
    CALL DRAW_CAR
    GOTO MAIN_LOOP
FP_RIGHT:
    BANKSEL BTN_EVENT
    BTFSS BTN_EVENT, BTN_RIGHT_B
    GOTO MAIN_LOOP
    BANKSEL PLAYER_LANE
    CMP_LIT PLAYER_LANE, 2
    BTFSC STATUS, 2
    GOTO MAIN_LOOP
    CALL ERASE_CAR
    BANKSEL PLAYER_LANE
    INCF PLAYER_LANE, F
    CALL DRAW_CAR
    GOTO MAIN_LOOP

FSM_PAUSE:
    BANKSEL BTN_EVENT
    BTFSS BTN_EVENT, BTN_SEL_B
    GOTO MAIN_LOOP
    BANKSEL GAME_STATE
    MOVLF STATE_PLAY, GAME_STATE
    GOTO MAIN_LOOP

FSM_GAMEOVER:
    BANKSEL NEW_BEST
    MOVF NEW_BEST, F
    BTFSC STATUS, 2
    GOTO FGO_BTN
    BANKSEL MENU_FLASH
    INCF MENU_FLASH, F
    MOVLW 39
    SUBWF MENU_FLASH, W
    BTFSS STATUS, 2
    GOTO FGO_BTN
    CLRF MENU_FLASH
    BANKSEL BLINK_FLAG
    INCF BLINK_FLAG, F
    BTFSS BLINK_FLAG, 0
    GOTO FGO_CLEAR_NR
    CALL DRAW_NEW_RECORD
    GOTO FGO_BTN
FGO_CLEAR_NR:
    MOVLF 4, DRAW_PAGE
    CALL DRAW_CLEAR_ROW

FGO_BTN:
    BANKSEL BTN_STATE
    BTFSS BTN_STATE, BTN_SEL_B
    GOTO MAIN_LOOP
    BANKSEL GAME_STATE
    MOVLF STATE_MENU, GAME_STATE
    CALL DRAW_MENU
    GOTO MAIN_LOOP  

FSM_MENU:
    BANKSEL MENU_FLASH
    INCF MENU_FLASH, F
    MOVLW 12
    SUBWF MENU_FLASH, W
    BTFSS STATUS, 2
    GOTO FM_BTN
    CLRF MENU_FLASH
    BANKSEL BLINK_FLAG
    INCF BLINK_FLAG, F
    BTFSS BLINK_FLAG, 0
    GOTO FM_FLASH_CLEAR
    CALL DRAW_MENU_CURSOR
    GOTO FM_BTN
FM_FLASH_CLEAR:
    MOVLF 6, DRAW_PAGE
    MOVLF 46, DRAW_X
    MOVLF FC_SPC, TEMP1
    CALL DRAW_CHAR

FM_BTN:
    BANKSEL BTN_EVENT
    BTFSS BTN_EVENT, BTN_SEL_B
    GOTO MAIN_LOOP
    CALL GAME_RESET
    GOTO MAIN_LOOP

PSECT fontCode, class=STRCODE, delta=2, reloc=256
FONT_TABLE:
    ADDWF PCL, F
    RETLW 0x00
    RETLW 0x00
    RETLW 0x00
    RETLW 0x00
    RETLW 0x00
    RETLW 0x41
    RETLW 0x22
    RETLW 0x14
    RETLW 0x08
    RETLW 0x00
    RETLW 0x7e
    RETLW 0x09
    RETLW 0x09
    RETLW 0x09
    RETLW 0x7e
    RETLW 0x7f
    RETLW 0x49
    RETLW 0x49
    RETLW 0x49
    RETLW 0x36
    RETLW 0x3e
    RETLW 0x41
    RETLW 0x41
    RETLW 0x41
    RETLW 0x22
    RETLW 0x7f
    RETLW 0x41
    RETLW 0x41
    RETLW 0x22
    RETLW 0x1c
    RETLW 0x7f
    RETLW 0x49
    RETLW 0x49
    RETLW 0x49
    RETLW 0x41
    RETLW 0x7f
    RETLW 0x09
    RETLW 0x09
    RETLW 0x01
    RETLW 0x01
    RETLW 0x3e
    RETLW 0x41
    RETLW 0x49
    RETLW 0x49
    RETLW 0x3a
    RETLW 0x7f
    RETLW 0x08
    RETLW 0x08
    RETLW 0x08
    RETLW 0x7f
    RETLW 0x41
    RETLW 0x41
    RETLW 0x7f
    RETLW 0x41
    RETLW 0x41
    RETLW 0x20
    RETLW 0x40
    RETLW 0x40
    RETLW 0x40
    RETLW 0x3f
    RETLW 0x7f
    RETLW 0x08
    RETLW 0x14
    RETLW 0x22
    RETLW 0x41
    RETLW 0x7f
    RETLW 0x40
    RETLW 0x40
    RETLW 0x40
    RETLW 0x40
    RETLW 0x7f
    RETLW 0x02
    RETLW 0x0c
    RETLW 0x02
    RETLW 0x7f
    RETLW 0x7f
    RETLW 0x02
    RETLW 0x04
    RETLW 0x08
    RETLW 0x7f
    RETLW 0x3e
    RETLW 0x41
    RETLW 0x41
    RETLW 0x41
    RETLW 0x3e
    RETLW 0x7f
    RETLW 0x09
    RETLW 0x09
    RETLW 0x09
    RETLW 0x06
    RETLW 0x3e
    RETLW 0x41
    RETLW 0x51
    RETLW 0x21
    RETLW 0x5e
    RETLW 0x7f
    RETLW 0x09
    RETLW 0x19
    RETLW 0x29
    RETLW 0x46
    RETLW 0x46
    RETLW 0x49
    RETLW 0x49
    RETLW 0x49
    RETLW 0x31
    RETLW 0x01
    RETLW 0x01
    RETLW 0x7f
    RETLW 0x01
    RETLW 0x01
    RETLW 0x3f
    RETLW 0x40
    RETLW 0x40
    RETLW 0x40
    RETLW 0x3f
    RETLW 0x1f
    RETLW 0x20
    RETLW 0x40
    RETLW 0x20
    RETLW 0x1f
    RETLW 0x7f
    RETLW 0x20
    RETLW 0x18
    RETLW 0x20
    RETLW 0x7f
    RETLW 0x41
    RETLW 0x22
    RETLW 0x1c
    RETLW 0x22
    RETLW 0x41
    RETLW 0x03
    RETLW 0x04
    RETLW 0x78
    RETLW 0x04
    RETLW 0x03
    RETLW 0x61
    RETLW 0x51
    RETLW 0x49
    RETLW 0x45
    RETLW 0x43
    RETLW 0x3e
    RETLW 0x51
    RETLW 0x49
    RETLW 0x45
    RETLW 0x3e
    RETLW 0x00
    RETLW 0x42
    RETLW 0x7f
    RETLW 0x40
    RETLW 0x00
    RETLW 0x42
    RETLW 0x61
    RETLW 0x51
    RETLW 0x49
    RETLW 0x46
    RETLW 0x21
    RETLW 0x41
    RETLW 0x49
    RETLW 0x49
    RETLW 0x36
    RETLW 0x18
    RETLW 0x14
    RETLW 0x12
    RETLW 0x7f
    RETLW 0x10
    RETLW 0x27
    RETLW 0x45
    RETLW 0x45
    RETLW 0x45
    RETLW 0x39
    RETLW 0x3c
    RETLW 0x4a
    RETLW 0x49
    RETLW 0x49
    RETLW 0x31
    RETLW 0x01
    RETLW 0x71
    RETLW 0x09
    RETLW 0x05
    RETLW 0x03
    RETLW 0x36
    RETLW 0x49
    RETLW 0x49
    RETLW 0x49
    RETLW 0x36
    RETLW 0x06
    RETLW 0x49
    RETLW 0x49
    RETLW 0x29
    RETLW 0x1e
    RETLW 0x00
    RETLW 0x36
    RETLW 0x36
    RETLW 0x00
    RETLW 0x00
    RETLW 0x14
    RETLW 0x14
    RETLW 0x14
    RETLW 0x14
    RETLW 0x14
    RETLW 0x00
    RETLW 0x5f
    RETLW 0x00
    RETLW 0x00
    RETLW 0x00
    RETLW 0x08
    RETLW 0x08
    RETLW 0x08
    RETLW 0x08
    RETLW 0x08


    END
