; LOAD_SPRITES
LOAD_SPRITES:
    MOVLF 0x00, CAR_TOP_0
    MOVLF 0x3C, CAR_TOP_1
    MOVLF 0x7E, CAR_TOP_2
    MOVLF 0x7E, CAR_TOP_3
    MOVLF 0x7E, CAR_TOP_4
    MOVLF 0x7E, CAR_TOP_5
    MOVLF 0x7E, CAR_TOP_6
    MOVLF 0x7E, CAR_TOP_7
    MOVLF 0x7E, CAR_TOP_8
    MOVLF 0x7E, CAR_TOP_9
    MOVLF 0x3C, CAR_TOP_A
    MOVLF 0x00, CAR_TOP_B
    BANKSEL CAR_BOT_0
    MOVLF 0x3C, CAR_BOT_0
    MOVLF 0x7E, CAR_BOT_1
    MOVLF 0x3C, CAR_BOT_2
    MOVLF 0xFF, CAR_BOT_3
    MOVLF 0xFF, CAR_BOT_4
    MOVLF 0xFF, CAR_BOT_5
    MOVLF 0xFF, CAR_BOT_6
    MOVLF 0xFF, CAR_BOT_7
    MOVLF 0xFF, CAR_BOT_8
    MOVLF 0x3C, CAR_BOT_9
    MOVLF 0x7E, CAR_BOT_A
    MOVLF 0x3C, CAR_BOT_B
    RETURN

